begin; select plan(12);
select has_table('public','kbo_sync_jobs','jobs exist');
select is((select count(*)::integer from public.kbo_sync_jobs),2,'two modes are separate');
select is((public.get_kbo_sync_status()->'secret'->>'configured')::boolean,false,'secret status only reports configured flag');
select lives_ok($$select public.admin_update_kbo_sync_job(null,'DAILY_SEED',time '08:30',true,true)$$,'job can pause/reschedule');
select is((select status from public.kbo_sync_jobs where mode='DAILY_SEED'),'PAUSED','pause persists');
select is(public.admin_run_kbo_sync(null,'DAILY_SEED',current_date,33,null)->>'error_code','MISSING_VAULT_SECRET','missing secret is distinct');
update public.kbo_sync_secret_status set configured=true,last_rotated_at=now() where id;
select is(public.admin_run_kbo_sync(null,'DAILY_SEED',current_date,33,null)->>'status','SUCCESS','manual seed can run');
select is(public.admin_run_kbo_sync(null,'HOURLY_REFRESH',current_date,33,null)->>'status','SUCCESS','refresh runs independently same date');
select is((select count(*)::integer from public.games where game_date=current_date),(select count(distinct id)::integer from public.games where game_date=current_date),'runs do not duplicate matches');
select is(public.admin_run_kbo_sync(null,'DAILY_SEED',current_date,33,(select max(id) from public.kbo_sync_runs where mode='DAILY_SEED'))->>'attempt','3','retry preserves inputs and increments attempt');
select ok((public.get_kbo_sync_status()->'secret') ? 'last_rotated_at','rotation metadata is exposed without plaintext');
select is((select count(distinct action)::integer from public.admin_audit_logs where action in('KBO_SYNC_JOB_UPDATE','KBO_SYNC_MANUAL_RUN','KBO_SYNC_RETRY')),3,'controls and runs are audited');
select * from finish(); rollback;
