begin;select plan(10);
select has_column('public','transactions','reverses_transaction_id','compensation link exists');
create temp table wallet_before as select balance from wallets where user_id=(select id from users limit 1) and season_id=1;
select lives_ok($$select public.admin_adjust_wallet(null,(select id from users limit 1),1,100,'보상','memo')$$,'grant succeeds');
select is((select balance from wallets where user_id=(select id from users limit 1) and season_id=1),(select balance+100 from wallet_before),'grant updates balance');
select lives_ok($$select public.admin_adjust_wallet(null,(select id from users limit 1),1,-50,'차감','memo')$$,'deduction succeeds');
select throws_ok($$select public.admin_adjust_wallet(null,(select id from users limit 1),1,-9999,'차감','memo')$$,'P0001','차감 후 잔액은 음수가 될 수 없습니다','negative balance blocked');
select lives_ok($$select public.admin_cancel_admin_grant(null,(select max(id) from transactions where type='ADMIN_GRANT'),'취소','memo')$$,'grant cancellation compensates');
select throws_ok($$select public.admin_cancel_admin_grant(null,(select reverses_transaction_id from transactions where type='ADMIN_REVERSAL' limit 1),'재취소','memo')$$,'P0001','이미 취소된 관리자 지급입니다','double cancellation blocked');
select ok(exists(select 1 from transactions where type='ADMIN_REVERSAL' and reverses_transaction_id is not null),'original remains linked');
select ok((public.get_wallet_diagnostics((select id from users limit 1),1)) ? 'ledger_sum','diagnostics expose ledger sum');
select is((select count(distinct action)::integer from admin_audit_logs where action in('WALLET_ADJUST','WALLET_GRANT_CANCEL')),2,'adjustments audited');
select * from finish();rollback;
