-- Additive admin-ops schema/RPCs.
-- Intentionally does NOT:
--   * revoke execute on existing season/market/grant RPCs
--   * replace login / execute_buy_order / execute_sell_order / activate_season
--   * run weekly grant cron or mutate wallets/markets/orders
--   * lock or delete games
-- Season 3 rows are left untouched.

do $$
begin
  create type public.admin_role as enum ('OWNER', 'OPERATOR', 'VIEWER');
exception
  when duplicate_object then null;
end;
$$;

create table if not exists public.admin_operators (
  id uuid primary key default gen_random_uuid(),
  username text not null,
  display_name text not null,
  role public.admin_role not null default 'VIEWER',
  password_hash text not null,
  is_active boolean not null default true,
  must_change_password boolean not null default true,
  created_by uuid references public.admin_operators(id) on delete set null,
  last_login_at timestamptz,
  password_changed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists admin_operators_username_lower_key
  on public.admin_operators (lower(username));

create table if not exists public.admin_sessions (
  id uuid primary key default gen_random_uuid(),
  operator_id uuid not null references public.admin_operators(id) on delete cascade,
  token_hash text not null unique,
  expires_at timestamptz not null,
  reauthenticated_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  revoked_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists public.admin_audit_logs (
  id bigint generated by default as identity primary key,
  request_id uuid not null default gen_random_uuid(),
  operator_id uuid references public.admin_operators(id) on delete set null,
  action text not null,
  target_type text,
  target_id text,
  before_state jsonb,
  after_state jsonb,
  success boolean not null,
  error_message text,
  ip_address inet,
  user_agent text,
  created_at timestamptz not null default now()
);

insert into public.admin_operators (
  id, username, display_name, role, password_hash, is_active, must_change_password
) values (
  '00000000-0000-0000-0000-000000000001',
  'admin',
  '운영진',
  'OWNER',
  'unused-hash-login-is-env-based',
  true,
  false
)
on conflict (id) do nothing;

alter table public.users
  add column if not exists is_active boolean not null default true,
  add column if not exists session_version integer not null default 1,
  add column if not exists deactivated_at timestamptz,
  add column if not exists deactivated_reason text;

insert into public.settings (key, value)
values ('member_initial_grant', '{"amount": 1000}'::jsonb)
on conflict (key) do nothing;

alter table public.teams
  add column if not exists is_active boolean not null default true,
  add column if not exists merged_into_team_id integer references public.teams(id),
  add column if not exists updated_at timestamptz not null default now();

alter table public.seasons
  add column if not exists initial_grant_amount numeric not null default 1000;

alter table public.seasons
  drop constraint if exists seasons_initial_grant_amount_check;
alter table public.seasons
  add constraint seasons_initial_grant_amount_check
  check (initial_grant_amount > 0);

alter table public.transactions
  add column if not exists reason text,
  add column if not exists internal_memo text,
  add column if not exists admin_operator_id uuid references public.admin_operators(id),
  add column if not exists reverses_transaction_id integer unique references public.transactions(id);

alter table public.transactions drop constraint if exists transactions_type_check;
alter table public.transactions add constraint transactions_type_check check (type in (
  'BUY','SELL','SETTLEMENT','SETTLEMENT_REVERSAL','SETTLEMENT_CORRECTION',
  'WEEKLY_GRANT','ADMIN_GRANT','ADMIN_DEDUCTION','ADMIN_REVERSAL',
  'SEASON_GRANT','SEASON_GRANT_REVERSAL'
));

create table if not exists public.team_aliases (
  id bigint generated by default as identity primary key,
  source text not null check (btrim(source) <> ''),
  alias text not null check (btrim(alias) <> ''),
  normalized_alias text generated always as (lower(btrim(alias))) stored,
  team_id integer not null references public.teams(id),
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create unique index if not exists team_aliases_active_source_alias_unique_idx
  on public.team_aliases (upper(btrim(source)), normalized_alias)
  where is_active;

create table if not exists public.team_mapping_requests (
  id bigint generated by default as identity primary key,
  source text not null check (btrim(source) <> ''),
  external_name text not null check (btrim(external_name) <> ''),
  normalized_external_name text generated always as (lower(btrim(external_name))) stored,
  status text not null default 'PENDING' check (status in ('PENDING','MAPPED','DISMISSED')),
  mapped_team_id integer references public.teams(id),
  occurrence_count integer not null default 1 check (occurrence_count > 0),
  first_seen_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  resolved_at timestamptz,
  resolved_by uuid references public.admin_operators(id) on delete set null
);

create table if not exists public.weekly_grant_policies (
  id integer generated by default as identity primary key,
  season_id integer not null unique references public.seasons(id),
  amount numeric not null check (amount > 0),
  weekday smallint not null check (weekday between 1 and 7),
  grant_time time not null,
  automatic_enabled boolean not null default false,
  is_paused boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create table if not exists public.weekly_grant_runs (
  id integer generated by default as identity primary key,
  season_id integer not null references public.seasons(id),
  round_key text not null,
  source text not null check (source in ('AUTO','MANUAL')),
  status text not null check (status in ('RUNNING','SUCCESS','FAILURE','SKIPPED')),
  scheduled_for timestamptz,
  recipient_count integer not null default 0,
  total_payout numeric not null default 0,
  failure_count integer not null default 0,
  error_message text,
  initiated_by uuid references public.admin_operators(id) on delete set null,
  started_at timestamptz not null default now(),
  completed_at timestamptz,
  unique (season_id, round_key)
);
create table if not exists public.weekly_grant_run_recipients (
  run_id integer not null references public.weekly_grant_runs(id) on delete cascade,
  user_id uuid not null references public.users(id),
  amount numeric not null check (amount > 0),
  balance_after numeric not null,
  primary key (run_id, user_id)
);

create table if not exists public.kbo_sync_jobs (
  mode text primary key check (mode in ('DAILY_SEED','HOURLY_REFRESH')),
  status text not null default 'DISABLED' check (status in ('ACTIVE','PAUSED','DISABLED')),
  schedule_kst time not null,
  enabled boolean not null default false,
  updated_at timestamptz not null default now()
);
create table if not exists public.kbo_sync_runs (
  id integer generated by default as identity primary key,
  mode text not null references public.kbo_sync_jobs(mode),
  target_date date not null,
  initial_price numeric not null,
  attempt integer not null default 1,
  status text not null check (status in ('SUCCESS','FAILURE')),
  error_code text,
  matches_created integer not null default 0,
  matches_updated integer not null default 0,
  skipped_items integer not null default 0,
  markets_created integer not null default 0,
  markets_closed integer not null default 0,
  error_count integer not null default 0,
  missing_candidates jsonb not null default '[]',
  duplicate_candidates jsonb not null default '[]',
  initiated_by uuid references public.admin_operators(id),
  created_at timestamptz not null default now(),
  unique(mode,target_date,initial_price,attempt)
);
create table if not exists public.kbo_sync_secret_status (
  id boolean primary key default true check (id),
  configured boolean not null default false,
  last_rotated_at timestamptz
);
insert into public.kbo_sync_jobs(mode,status,schedule_kst,enabled,updated_at) values
  ('DAILY_SEED','DISABLED','00:10',false,now()),
  ('HOURLY_REFRESH','DISABLED','01:00',false,now())
on conflict (mode) do nothing;
insert into public.kbo_sync_secret_status(id,configured) values (true,false)
on conflict (id) do nothing;

create table if not exists public.settlement_events (
  id integer generated by default as identity primary key,
  market_id integer not null,
  original_result text not null,
  position_snapshot jsonb not null,
  payout_snapshot jsonb not null,
  created_at timestamptz not null default now(),
  unique(market_id)
);
create table if not exists public.settlement_recoveries (
  id integer generated by default as identity primary key,
  event_id integer not null references public.settlement_events(id),
  correct_result text not null,
  reason text not null,
  operator_id uuid references public.admin_operators(id),
  status text not null,
  created_at timestamptz default now(),
  unique(event_id)
);
create table if not exists public.season_incidents (
  id integer generated by default as identity primary key,
  new_season_id integer not null,
  previous_season_id integer not null,
  reason text not null,
  operator_id uuid references public.admin_operators(id),
  before_state jsonb,
  after_state jsonb,
  created_at timestamptz default now()
);

insert into public.weekly_grant_policies (
  season_id, amount, weekday, grant_time, automatic_enabled, is_paused
)
select id, 300, 1, time '00:00', false, true
from public.seasons
where status = 'ACTIVE'
on conflict (season_id) do nothing;

create or replace function public.require_admin_operator(
  p_actor_id uuid,
  p_owner_only boolean default false
)
returns public.admin_role
language plpgsql
security definer
set search_path = public
as $$
begin
  -- Shared-password admin: no operator-account table lookup.
  return 'OWNER'::public.admin_role;
end;
$$;

-- from 36.sql
create or replace function public.admin_write_audit(
  p_operator_id uuid,
  p_action text,
  p_target_type text,
  p_target_id text,
  p_before_state jsonb,
  p_after_state jsonb,
  p_success boolean,
  p_error_message text,
  p_ip_address inet,
  p_user_agent text
)
returns void
language sql
security definer
set search_path = public
as $$
  insert into public.admin_audit_logs (
    operator_id,
    action,
    target_type,
    target_id,
    before_state,
    after_state,
    success,
    error_message,
    ip_address,
    user_agent
  )
  values (
    p_operator_id,
    p_action,
    p_target_type,
    p_target_id,
    p_before_state,
    p_after_state,
    p_success,
    p_error_message,
    p_ip_address,
    p_user_agent
  );
$$;

create or replace function public.admin_apply_game_data(
  p_operator_id uuid,
  p_payload jsonb,
  p_ip_address inet,
  p_user_agent text
)
returns jsonb
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  v_action text := p_payload ->> 'action';
  v_before jsonb;
  v_after jsonb;
  v_error text;
  v_game jsonb;
  v_game_id integer;
  v_target_date date;
  v_keep_ids integer[];
  v_inserted_ids integer[] := array[]::integer[];
  v_deleted_ids integer[] := array[]::integer[];
begin
  begin
    if not exists (
      select 1
      from public.admin_operators
      where id = p_operator_id
        and is_active
        and not must_change_password
        and role in ('OWNER', 'OPERATOR')
    ) then
      raise exception '관리자 변경 권한이 없습니다';
    end if;

    if v_action = 'create_teams' then
      with inserted as (
        insert into public.teams (name, short_name, team_color)
        select
          team ->> 'name',
          team ->> 'short_name',
          team ->> 'team_color'
        from jsonb_array_elements(p_payload -> 'teams') as team
        returning id, name, short_name, team_color
      )
      select coalesce(jsonb_agg(to_jsonb(inserted)), '[]'::jsonb)
      into v_after
      from inserted;

      perform public.admin_write_audit(
        p_operator_id,
        'ADMIN_TEAMS_CREATED',
        'team',
        null,
        null,
        v_after,
        true,
        null,
        p_ip_address,
        p_user_agent
      );
      return jsonb_build_object('success', true, 'teams', v_after);
    end if;

    if v_action <> 'save_games' then
      raise exception '지원하지 않는 경기 데이터 작업입니다';
    end if;

    v_target_date := (p_payload ->> 'targetDate')::date;
    perform pg_advisory_xact_lock(
      hashtextextended(
        'admin-game-date:' || v_target_date::text,
        0
      )
    );

    if exists (
      select 1
      from jsonb_array_elements(p_payload -> 'games') as game
      where (game ->> 'game_date')::date <> v_target_date
    ) then
      raise exception '모든 경기 날짜는 저장 대상 날짜와 같아야 합니다';
    end if;

    select coalesce(array_agg((game ->> 'id')::integer), array[]::integer[])
    into v_keep_ids
    from jsonb_array_elements(p_payload -> 'games') as game
    where game ? 'id';

    perform id
    from public.games
    where game_date = v_target_date
    for update;

    select coalesce(jsonb_agg(to_jsonb(g) order by g.id), '[]'::jsonb)
    into v_before
    from public.games g
    where g.game_date = v_target_date;

    if exists (
      select 1
      from public.games g
      join public.markets m on m.game_id = g.id
      where g.game_date = v_target_date
        and not (g.id = any(v_keep_ids))
    ) then
      raise exception '연결된 마켓이 있는 경기는 이 화면에서 삭제할 수 없습니다';
    end if;

    with deleted as (
      delete from public.games g
      where g.game_date = v_target_date
        and not (g.id = any(v_keep_ids))
      returning g.id
    )
    select coalesce(array_agg(id), array[]::integer[])
    into v_deleted_ids
    from deleted;

    for v_game in
      select value
      from jsonb_array_elements(p_payload -> 'games')
    loop
      if v_game ? 'id' then
        v_game_id := (v_game ->> 'id')::integer;
        update public.games
        set
          game_date = (v_game ->> 'game_date')::date,
          game_time = nullif(v_game ->> 'game_time', '')::time,
          home_team_id = (v_game ->> 'home_team_id')::integer,
          away_team_id = (v_game ->> 'away_team_id')::integer,
          home_pitcher = nullif(v_game ->> 'home_pitcher', ''),
          away_pitcher = nullif(v_game ->> 'away_pitcher', ''),
          home_score = nullif(v_game ->> 'home_score', '')::integer,
          away_score = nullif(v_game ->> 'away_score', '')::integer,
          game_status = (v_game ->> 'game_status')::public.game_status,
          updated_at = now()
        where id = v_game_id
          and game_date = v_target_date;

        if not found then
          raise exception '경기를 찾을 수 없습니다: %', v_game_id;
        end if;
      else
        insert into public.games (
          game_date,
          game_time,
          home_team_id,
          away_team_id,
          home_pitcher,
          away_pitcher,
          home_score,
          away_score,
          game_status
        )
        values (
          (v_game ->> 'game_date')::date,
          nullif(v_game ->> 'game_time', '')::time,
          (v_game ->> 'home_team_id')::integer,
          (v_game ->> 'away_team_id')::integer,
          nullif(v_game ->> 'home_pitcher', ''),
          nullif(v_game ->> 'away_pitcher', ''),
          nullif(v_game ->> 'home_score', '')::integer,
          nullif(v_game ->> 'away_score', '')::integer,
          (v_game ->> 'game_status')::public.game_status
        )
        returning id into v_game_id;
        v_inserted_ids := array_append(v_inserted_ids, v_game_id);
      end if;
    end loop;

    select coalesce(jsonb_agg(to_jsonb(g) order by g.id), '[]'::jsonb)
    into v_after
    from public.games g
    where g.game_date = v_target_date;

    perform public.admin_write_audit(
      p_operator_id,
      'ADMIN_GAMES_SAVED',
      'game',
      v_target_date::text,
      v_before,
      jsonb_build_object(
        'games', v_after,
        'insertedIds', v_inserted_ids,
        'deletedIds', v_deleted_ids
      ),
      true,
      null,
      p_ip_address,
      p_user_agent
    );

    return jsonb_build_object(
      'success', true,
      'insertedIds', to_jsonb(v_inserted_ids),
      'deletedIds', to_jsonb(v_deleted_ids)
    );
  exception
    when others then
      get stacked diagnostics v_error = message_text;
      perform public.admin_write_audit(
        p_operator_id,
        case
          when v_action = 'create_teams' then 'ADMIN_TEAMS_CREATED'
          else 'ADMIN_GAMES_SAVED'
        end,
        case
          when v_action = 'create_teams' then 'team'
          else 'game'
        end,
        coalesce(v_target_date::text, null),
        v_before,
        null,
        false,
        v_error,
        p_ip_address,
        p_user_agent
      );
      return jsonb_build_object('success', false, 'error', v_error);
  end;
end;
$$;

-- from 37.sql
create or replace function public.admin_upsert_member(
  p_actor_id uuid,
  p_member jsonb,
  p_reset_password boolean default false
)
returns jsonb
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  v_before public.users%rowtype;
  v_after public.users%rowtype;
  v_student_number bigint;
  v_username text;
  v_phone text;
  v_department text;
  v_team_id integer;
  v_action text;
  v_active_season_id integer;
  v_initial_grant numeric;
  v_inserted_wallet_id uuid;
begin
  perform public.require_admin_operator(p_actor_id);

  if coalesce(p_member->>'student_number', '') !~ '^[0-9]+$' then
    raise exception '학번은 숫자만 입력해야 합니다';
  end if;
  v_student_number := (p_member->>'student_number')::bigint;
  v_username := btrim(coalesce(p_member->>'username', ''));
  v_phone := regexp_replace(coalesce(p_member->>'phone_number', ''), '[^0-9]', '', 'g');
  v_department := btrim(coalesce(p_member->>'department', ''));

  if coalesce(p_member->>'favorite_team_id', '') !~ '^[0-9]+$' then
    raise exception '선호팀을 선택해주세요';
  end if;
  v_team_id := (p_member->>'favorite_team_id')::integer;

  if v_username = '' then
    raise exception '이름은 필수입니다';
  end if;
  if v_department = '' then
    raise exception '학과는 필수입니다';
  end if;
  if v_phone !~ '^01[016789][0-9]{7,8}$' then
    raise exception '전화번호 형식이 올바르지 않습니다';
  end if;
  if not exists (select 1 from public.teams where id = v_team_id) then
    raise exception '선호팀 정보를 찾을 수 없습니다';
  end if;

  select *
  into v_before
  from public.users
  where student_number = v_student_number
  for update;

  if not found then
    insert into public.users (
      student_number,
      username,
      phone_number,
      department,
      type,
      favorite_team_id,
      password_hash,
      password_changed,
      is_active,
      session_version
    )
    values (
      v_student_number,
      v_username,
      v_phone,
      v_department,
      'STUDENT',
      v_team_id,
      encode(digest(v_phone, 'sha256'), 'hex'),
      false,
      true,
      1
    )
    returning * into v_after;
    v_action := 'CREATE';

    select id
    into v_active_season_id
    from public.seasons
    where status = 'ACTIVE'
    limit 1;

    if v_active_season_id is null then
      raise exception '활성 시즌을 찾을 수 없습니다';
    end if;

    select coalesce((value->>'amount')::numeric, 1000)
    into v_initial_grant
    from public.settings
    where key = 'member_initial_grant';
    v_initial_grant := coalesce(v_initial_grant, 1000);

    insert into public.wallets (
      user_id, season_id, balance, created_at, updated_at
    )
    values (
      v_after.id, v_active_season_id, v_initial_grant, now(), now()
    )
    on conflict (user_id, season_id) do nothing
    returning id into v_inserted_wallet_id;

    if v_inserted_wallet_id is not null then
      insert into public.transactions (
        user_id, type, amount, balance_after, reference_id,
        description, season_id
      )
      values (
        v_after.id, 'SEASON_GRANT', v_initial_grant, v_initial_grant, null,
        '신규 회원 시즌 시작 코인 지급', v_active_season_id
      );
    end if;
  else
    update public.users
    set
      username = v_username,
      phone_number = v_phone,
      department = v_department,
      favorite_team_id = v_team_id,
      password_hash = case
        when p_reset_password then encode(digest(v_phone, 'sha256'), 'hex')
        else password_hash
      end,
      password_changed = case
        when p_reset_password then false
        else password_changed
      end,
      session_version = case
        when p_reset_password then session_version + 1
        else session_version
      end,
      updated_at = now()
    where id = v_before.id
    returning * into v_after;
    v_action := 'UPDATE';
  end if;

  insert into public.admin_audit_logs (
    operator_id, action, target_type, target_id,
    before_state, after_state, success
  )
  values (
    p_actor_id,
    'ADMIN_MEMBER_' || v_action,
    'user',
    v_after.id::text,
    case when v_action = 'UPDATE' then to_jsonb(v_before) else null end,
    to_jsonb(v_after) - 'password_hash',
    true
  );

  return jsonb_build_object(
    'success', true,
    'action', v_action,
    'user_id', v_after.id,
    'student_number', v_after.student_number,
    'password_reset', p_reset_password,
    'wallet_created', v_inserted_wallet_id is not null
  );
end;
$$;

create or replace function public.admin_bulk_upsert_members(
  p_actor_id uuid,
  p_rows jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  v_row jsonb;
  v_result jsonb;
  v_results jsonb := '[]'::jsonb;
begin
  perform public.require_admin_operator(p_actor_id);
  if jsonb_typeof(p_rows) <> 'array' then
    raise exception '회원 일괄 데이터는 배열이어야 합니다';
  end if;

  for v_row in select value from jsonb_array_elements(p_rows)
  loop
    v_result := public.admin_upsert_member(
      p_actor_id,
      v_row,
      coalesce((v_row->>'reset_password')::boolean, false)
    );
    v_results := v_results || jsonb_build_array(v_result);
  end loop;

  insert into public.admin_audit_logs (
    operator_id, action, target_type, after_state, success
  )
  values (
    p_actor_id,
    'ADMIN_MEMBER_BULK_APPLY',
    'user',
    jsonb_build_object('results', v_results),
    true
  );

  return jsonb_build_object('success', true, 'results', v_results);
end;
$$;

create or replace function public.admin_member_impact(p_user_id uuid)
returns jsonb
language sql
security definer
set search_path = public, extensions
as $$
  select jsonb_build_object(
    'open_position_count',
    (
      select count(*)
      from public.positions p
      join public.markets m on m.id = p.market_id
      where p.user_id = p_user_id
        and p.quantity > 0
        and m.status in ('OPEN', 'CLOSED')
    ),
    'active_wallet_balance',
    (
      select w.balance
      from public.wallets w
      join public.seasons s on s.id = w.season_id and s.status = 'ACTIVE'
      where w.user_id = p_user_id
      limit 1
    ),
    'has_active_wallet',
    exists (
      select 1
      from public.wallets w
      join public.seasons s on s.id = w.season_id and s.status = 'ACTIVE'
      where w.user_id = p_user_id
    )
  );
$$;

create or replace function public.admin_set_member_active(
  p_actor_id uuid,
  p_user_id uuid,
  p_is_active boolean,
  p_confirm_open_positions boolean default false,
  p_reason text default null
)
returns jsonb
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  v_before public.users%rowtype;
  v_after public.users%rowtype;
  v_impact jsonb;
begin
  perform public.require_admin_operator(p_actor_id);
  select * into v_before from public.users where id = p_user_id for update;
  if not found then
    raise exception '회원 정보를 찾을 수 없습니다';
  end if;

  v_impact := public.admin_member_impact(p_user_id);
  if not p_is_active
     and (v_impact->>'open_position_count')::integer > 0
     and not p_confirm_open_positions then
    raise exception '미정산 포지션이 있어 영향 확인이 필요합니다';
  end if;

  update public.users
  set
    is_active = p_is_active,
    session_version = session_version + 1,
    deactivated_at = case when p_is_active then null else now() end,
    deactivated_reason = case when p_is_active then null else p_reason end,
    updated_at = now()
  where id = p_user_id
  returning * into v_after;

  insert into public.admin_audit_logs (
    operator_id, action, target_type, target_id,
    before_state, after_state, success
  )
  values (
    p_actor_id,
    case when p_is_active
      then 'ADMIN_MEMBER_REACTIVATED'
      else 'ADMIN_MEMBER_DEACTIVATED'
    end,
    'user',
    p_user_id::text,
    to_jsonb(v_before) - 'password_hash',
    jsonb_build_object(
      'member', to_jsonb(v_after) - 'password_hash',
      'impact', v_impact
    ),
    true
  );

  return jsonb_build_object(
    'success', true,
    'user_id', p_user_id,
    'is_active', p_is_active,
    'session_version', v_after.session_version,
    'impact', v_impact
  );
end;
$$;

create or replace function public.admin_repair_member_wallet(
  p_actor_id uuid,
  p_user_id uuid
)
returns jsonb
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  v_user public.users%rowtype;
  v_season_id integer;
  v_initial_grant numeric;
  v_wallet_id uuid;
begin
  perform public.require_admin_operator(p_actor_id);
  select * into v_user from public.users where id = p_user_id for update;
  if not found then
    raise exception '회원 정보를 찾을 수 없습니다';
  end if;
  if not v_user.is_active then
    raise exception '비활성 회원의 지갑은 복구할 수 없습니다';
  end if;

  select id into v_season_id
  from public.seasons where status = 'ACTIVE' limit 1;
  if v_season_id is null then
    raise exception '활성 시즌이 없습니다';
  end if;

  select coalesce((value->>'amount')::numeric, 1000)
  into v_initial_grant
  from public.settings where key = 'member_initial_grant';
  v_initial_grant := coalesce(v_initial_grant, 1000);

  insert into public.wallets (
    user_id, season_id, balance, created_at, updated_at
  )
  values (p_user_id, v_season_id, v_initial_grant, now(), now())
  on conflict (user_id, season_id) do nothing
  returning id into v_wallet_id;

  if v_wallet_id is not null then
    insert into public.transactions (
      user_id, type, amount, balance_after, reference_id,
      description, season_id
    )
    values (
      p_user_id, 'SEASON_GRANT', v_initial_grant, v_initial_grant, null,
      '누락 활성 시즌 지갑 복구', v_season_id
    );
  end if;

  insert into public.admin_audit_logs (
    operator_id, action, target_type, target_id, after_state, success
  )
  values (
    p_actor_id,
    'ADMIN_MEMBER_WALLET_REPAIRED',
    'user',
    p_user_id::text,
    jsonb_build_object(
      'season_id', v_season_id,
      'created', v_wallet_id is not null,
      'initial_grant', v_initial_grant
    ),
    true
  );

  return jsonb_build_object(
    'success', true,
    'user_id', p_user_id,
    'season_id', v_season_id,
    'created', v_wallet_id is not null,
    'initial_grant', v_initial_grant
  );
end;
$$;

-- from 38.sql
create or replace function public.admin_upsert_team(
  p_operator_id uuid,
  p_team_id integer,
  p_name text,
  p_short_name text,
  p_team_color text
)
returns public.teams
language plpgsql
security definer
set search_path = public
as $$
declare
  v_before public.teams;
  v_team public.teams;
begin
  if btrim(coalesce(p_name, '')) = '' then
    raise exception '팀 이름을 입력해주세요';
  end if;
  if btrim(coalesce(p_short_name, '')) = '' then
    raise exception '팀 약칭을 입력해주세요';
  end if;
  if p_team_color !~ '^#[0-9A-F]{6}$' then
    raise exception '팀 색상은 #RRGGBB 형식이어야 합니다';
  end if;

  if p_team_id is null then
    insert into public.teams (name, short_name, team_color)
    values (btrim(p_name), btrim(p_short_name), p_team_color)
    returning * into v_team;

    insert into public.admin_audit_logs (
      operator_id, action, target_type, target_id, after_state, success
    )
    values (
      p_operator_id,
      'TEAM_CREATE',
      'team',
      v_team.id::text,
      to_jsonb(v_team),
      true
    );
  else
    select *
    into v_before
    from public.teams
    where id = p_team_id
    for update;

    if not found then
      raise exception '팀을 찾을 수 없습니다';
    end if;
    if not v_before.is_active then
      raise exception '비활성 팀은 수정할 수 없습니다';
    end if;

    update public.teams
    set name = btrim(p_name),
        short_name = btrim(p_short_name),
        team_color = p_team_color,
        updated_at = now()
    where id = p_team_id
    returning * into v_team;

    insert into public.admin_audit_logs (
      operator_id, action, target_type, target_id,
      before_state, after_state, success
    )
    values (
      p_operator_id,
      'TEAM_UPDATE',
      'team',
      v_team.id::text,
      to_jsonb(v_before),
      to_jsonb(v_team),
      true
    );
  end if;

  return v_team;
end;
$$;

create or replace function public.admin_upsert_team_alias(
  p_operator_id uuid,
  p_alias_id bigint,
  p_source text,
  p_alias text,
  p_team_id integer
)
returns public.team_aliases
language plpgsql
security definer
set search_path = public
as $$
declare
  v_before public.team_aliases;
  v_alias public.team_aliases;
begin
  if btrim(coalesce(p_source, '')) = '' then
    raise exception '소스를 입력해주세요';
  end if;
  if btrim(coalesce(p_alias, '')) = '' then
    raise exception '별칭을 입력해주세요';
  end if;
  if not exists (
    select 1 from public.teams where id = p_team_id and is_active
  ) then
    raise exception '활성 팀을 찾을 수 없습니다';
  end if;

  if p_alias_id is null then
    insert into public.team_aliases (source, alias, team_id)
    values (upper(btrim(p_source)), btrim(p_alias), p_team_id)
    returning * into v_alias;

    insert into public.admin_audit_logs (
      operator_id, action, target_type, target_id, after_state, success
    )
    values (
      p_operator_id,
      'TEAM_ALIAS_CREATE',
      'team_alias',
      v_alias.id::text,
      to_jsonb(v_alias),
      true
    );
  else
    select *
    into v_before
    from public.team_aliases
    where id = p_alias_id
    for update;

    if not found then
      raise exception '팀 별칭을 찾을 수 없습니다';
    end if;

    update public.team_aliases
    set source = upper(btrim(p_source)),
        alias = btrim(p_alias),
        team_id = p_team_id,
        is_active = true,
        updated_at = now()
    where id = p_alias_id
    returning * into v_alias;

    insert into public.admin_audit_logs (
      operator_id, action, target_type, target_id,
      before_state, after_state, success
    )
    values (
      p_operator_id,
      'TEAM_ALIAS_UPDATE',
      'team_alias',
      v_alias.id::text,
      to_jsonb(v_before),
      to_jsonb(v_alias),
      true
    );
  end if;

  return v_alias;
end;
$$;

create or replace function public.resolve_team_mappings(
  p_source text,
  p_external_names text[]
)
returns table (
  external_name text,
  mapping_status text,
  team_id integer,
  team_name text,
  request_id bigint
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_name text;
  v_team public.teams;
  v_request_id bigint;
begin
  if btrim(coalesce(p_source, '')) = '' then
    raise exception '소스를 입력해주세요';
  end if;

  for v_name in
    select distinct btrim(value)
    from unnest(coalesce(p_external_names, array[]::text[])) as names(value)
    where btrim(value) <> ''
  loop
    select t.*
    into v_team
    from public.teams t
    where t.is_active
      and (
        lower(btrim(t.name)) = lower(v_name)
        or lower(btrim(t.short_name)) = lower(v_name)
      )
    limit 1;

    if not found then
      select t.*
      into v_team
      from public.team_aliases a
      join public.teams t on t.id = a.team_id
      where a.is_active
        and t.is_active
        and upper(btrim(a.source)) = upper(btrim(p_source))
        and a.normalized_alias = lower(v_name)
      limit 1;
    end if;

    if found then
      external_name := v_name;
      mapping_status := 'MAPPED';
      team_id := v_team.id;
      team_name := v_team.name;
      request_id := null;
      return next;
    else
      insert into public.team_mapping_requests (
        source, external_name, status
      )
      values (
        upper(btrim(p_source)), v_name, 'PENDING'
      )
      on conflict (
        (upper(btrim(source))),
        normalized_external_name
      ) where status = 'PENDING'
      do update
      set occurrence_count =
            public.team_mapping_requests.occurrence_count + 1,
          last_seen_at = now(),
          external_name = excluded.external_name
      returning id into v_request_id;

      external_name := v_name;
      mapping_status := 'PENDING';
      team_id := null;
      team_name := null;
      request_id := v_request_id;
      return next;
    end if;
  end loop;
end;
$$;

create or replace function public.admin_approve_team_mapping(
  p_operator_id uuid,
  p_request_id bigint,
  p_team_id integer,
  p_name text,
  p_short_name text,
  p_team_color text
)
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  v_request public.team_mapping_requests;
  v_team public.teams;
  v_team_id integer;
  v_alias public.team_aliases;
begin
  select *
  into v_request
  from public.team_mapping_requests
  where id = p_request_id
    and status = 'PENDING'
  for update;

  if not found then
    raise exception '대기 중인 매핑 요청을 찾을 수 없습니다';
  end if;

  if p_team_id is null then
    v_team := public.admin_upsert_team(
      p_operator_id,
      null,
      p_name,
      p_short_name,
      p_team_color
    );
    v_team_id := v_team.id;
  else
    select *
    into v_team
    from public.teams
    where id = p_team_id and is_active;

    if not found then
      raise exception '매핑할 활성 팀을 찾을 수 없습니다';
    end if;
    v_team_id := v_team.id;
  end if;

  v_alias := public.admin_upsert_team_alias(
    p_operator_id,
    null,
    v_request.source,
    v_request.external_name,
    v_team_id
  );

  update public.team_mapping_requests
  set status = 'MAPPED',
      mapped_team_id = v_team_id,
      resolved_at = now(),
      resolved_by = p_operator_id
  where id = p_request_id;

  insert into public.admin_audit_logs (
    operator_id, action, target_type, target_id,
    before_state, after_state, success
  )
  values (
    p_operator_id,
    'TEAM_MAPPING_APPROVE',
    'team_mapping_request',
    p_request_id::text,
    to_jsonb(v_request),
    jsonb_build_object(
      'status', 'MAPPED',
      'team_id', v_team_id,
      'alias_id', v_alias.id
    ),
    true
  );

  return v_team_id;
end;
$$;

create or replace function public.get_team_merge_impact(
  p_source_team_id integer,
  p_target_team_id integer
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_source public.teams;
  v_target public.teams;
begin
  if p_source_team_id = p_target_team_id then
    raise exception '서로 다른 팀을 선택해주세요';
  end if;

  select * into v_source
  from public.teams
  where id = p_source_team_id and is_active;

  select * into v_target
  from public.teams
  where id = p_target_team_id and is_active;

  if v_source.id is null or v_target.id is null then
    raise exception '병합할 활성 팀을 찾을 수 없습니다';
  end if;

  return jsonb_build_object(
    'source_team_id', v_source.id,
    'source_team_name', v_source.name,
    'target_team_id', v_target.id,
    'target_team_name', v_target.name,
    'affected_matches', (
      select count(*)
      from public.games
      where home_team_id = v_source.id or away_team_id = v_source.id
    ),
    'affected_members', (
      select count(*)
      from public.users
      where favorite_team_id = v_source.id
    ),
    'affected_aliases', (
      select count(*)
      from public.team_aliases
      where team_id = v_source.id and is_active
    )
  );
end;
$$;

create or replace function public.admin_merge_teams(
  p_operator_id uuid,
  p_source_team_id integer,
  p_target_team_id integer
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_source public.teams;
  v_target public.teams;
  v_impact jsonb;
  v_moved_home integer;
  v_moved_away integer;
  v_moved_members integer;
begin
  if p_source_team_id = p_target_team_id then
    raise exception '서로 다른 팀을 선택해주세요';
  end if;

  select * into v_source
  from public.teams
  where id = p_source_team_id and is_active
  for update;

  select * into v_target
  from public.teams
  where id = p_target_team_id and is_active
  for update;

  if v_source.id is null or v_target.id is null then
    raise exception '병합할 활성 팀을 찾을 수 없습니다';
  end if;

  if exists (
    select 1
    from public.games
    where (
      home_team_id = v_source.id and away_team_id = v_target.id
    ) or (
      home_team_id = v_target.id and away_team_id = v_source.id
    )
  ) then
    raise exception '두 팀이 같은 경기의 홈/원정으로 연결되어 있어 병합할 수 없습니다';
  end if;

  v_impact := public.get_team_merge_impact(
    p_source_team_id,
    p_target_team_id
  );

  update public.games
  set home_team_id = v_target.id
  where home_team_id = v_source.id;
  get diagnostics v_moved_home = row_count;

  update public.games
  set away_team_id = v_target.id
  where away_team_id = v_source.id;
  get diagnostics v_moved_away = row_count;

  update public.users
  set favorite_team_id = v_target.id
  where favorite_team_id = v_source.id;
  get diagnostics v_moved_members = row_count;

  delete from public.team_aliases source_alias
  using public.team_aliases target_alias
  where source_alias.team_id = v_source.id
    and source_alias.is_active
    and target_alias.team_id = v_target.id
    and target_alias.is_active
    and upper(btrim(source_alias.source)) =
        upper(btrim(target_alias.source))
    and source_alias.normalized_alias = target_alias.normalized_alias;

  update public.team_aliases
  set team_id = v_target.id,
      updated_at = now()
  where team_id = v_source.id;

  update public.team_mapping_requests
  set mapped_team_id = v_target.id
  where mapped_team_id = v_source.id;

  update public.teams
  set is_active = false,
      merged_into_team_id = v_target.id,
      updated_at = now()
  where id = v_source.id;

  insert into public.admin_audit_logs (
    operator_id, action, target_type, target_id,
    before_state, after_state, success
  )
  values (
    p_operator_id,
    'TEAM_MERGE',
    'team',
    v_target.id::text,
    jsonb_build_object(
      'source', to_jsonb(v_source),
      'target', to_jsonb(v_target),
      'impact', v_impact
    ),
    jsonb_build_object(
      'source_team_id', v_source.id,
      'target_team_id', v_target.id,
      'moved_home_matches', v_moved_home,
      'moved_away_matches', v_moved_away,
      'moved_members', v_moved_members
    ),
    true
  );

  insert into public.admin_audit_logs (
    operator_id, action, target_type, target_id,
    before_state, after_state, success
  )
  values (
    p_operator_id,
    'TEAM_DEACTIVATE',
    'team',
    v_source.id::text,
    to_jsonb(v_source),
    jsonb_build_object(
      'is_active', false,
      'merged_into_team_id', v_target.id
    ),
    true
  );

  return v_impact || jsonb_build_object(
    'moved_home_matches', v_moved_home,
    'moved_away_matches', v_moved_away,
    'moved_members', v_moved_members
  );
end;
$$;

-- from 39.sql
create or replace function public.assert_valid_season_draft(
  p_excluded_season_id integer,
  p_name text,
  p_start_date date,
  p_end_date date,
  p_initial_grant_amount numeric
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if btrim(coalesce(p_name, '')) = '' then
    raise exception '시즌 이름을 입력해주세요';
  end if;
  if p_start_date is null or p_end_date is null then
    raise exception '시작일과 종료일을 모두 입력해주세요';
  end if;
  if p_start_date >= p_end_date then
    raise exception '시작일은 종료일보다 빨라야 합니다';
  end if;
  if p_initial_grant_amount is null or p_initial_grant_amount <= 0 then
    raise exception '초기 지급액은 0보다 커야 합니다';
  end if;
  if exists (
    select 1
    from public.seasons s
    where s.id is distinct from p_excluded_season_id
      and s.start_date is not null
      and s.end_date is not null
      and daterange(s.start_date, s.end_date, '[]')
        && daterange(p_start_date, p_end_date, '[]')
  ) then
    raise exception '다른 시즌 기간과 겹칩니다';
  end if;
end;
$$;

create or replace function public.admin_create_draft_season(
  p_operator_id uuid,
  p_name text,
  p_start_date date,
  p_end_date date,
  p_initial_grant_amount numeric
)
returns public.seasons
language plpgsql
security definer
set search_path = public
as $$
declare
  v_season public.seasons;
begin
  perform public.assert_valid_season_draft(
    null,
    p_name,
    p_start_date,
    p_end_date,
    p_initial_grant_amount
  );

  if exists (select 1 from public.seasons where status = 'DRAFT') then
    raise exception '이미 DRAFT 시즌이 존재합니다';
  end if;

  insert into public.seasons (
    name,
    start_date,
    end_date,
    status,
    initial_grant_amount
  )
  values (
    btrim(p_name),
    p_start_date,
    p_end_date,
    'DRAFT',
    p_initial_grant_amount
  )
  returning * into v_season;

  insert into public.admin_audit_logs (
    operator_id, action, target_type, target_id, after_state, success
  )
  values (
    p_operator_id,
    'SEASON_DRAFT_CREATE',
    'season',
    v_season.id::text,
    to_jsonb(v_season),
    true
  );

  return v_season;
end;
$$;

create or replace function public.admin_update_draft_season(
  p_operator_id uuid,
  p_season_id integer,
  p_name text,
  p_start_date date,
  p_end_date date,
  p_initial_grant_amount numeric
)
returns public.seasons
language plpgsql
security definer
set search_path = public
as $$
declare
  v_before public.seasons;
  v_season public.seasons;
begin
  select *
  into v_before
  from public.seasons
  where id = p_season_id
  for update;

  if not found then
    raise exception '시즌을 찾을 수 없습니다';
  end if;
  if v_before.status <> 'DRAFT' then
    raise exception 'DRAFT 시즌만 수정할 수 있습니다';
  end if;

  perform public.assert_valid_season_draft(
    p_season_id,
    p_name,
    p_start_date,
    p_end_date,
    p_initial_grant_amount
  );

  update public.seasons
  set name = btrim(p_name),
      start_date = p_start_date,
      end_date = p_end_date,
      initial_grant_amount = p_initial_grant_amount
  where id = p_season_id
  returning * into v_season;

  insert into public.admin_audit_logs (
    operator_id, action, target_type, target_id,
    before_state, after_state, success
  )
  values (
    p_operator_id,
    'SEASON_DRAFT_UPDATE',
    'season',
    v_season.id::text,
    to_jsonb(v_before),
    to_jsonb(v_season),
    true
  );

  return v_season;
end;
$$;

create or replace function public.get_draft_season_delete_impact(
  p_season_id integer
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_season public.seasons;
begin
  select *
  into v_season
  from public.seasons
  where id = p_season_id;

  if not found then
    raise exception '시즌을 찾을 수 없습니다';
  end if;
  if v_season.status <> 'DRAFT' then
    raise exception 'DRAFT 시즌만 삭제할 수 있습니다';
  end if;

  return jsonb_build_object(
    'season_id', v_season.id,
    'season_name', v_season.name,
    'linked_matches', (
      select count(distinct game_id)
      from public.markets
      where season_id = v_season.id
    ),
    'linked_markets', (
      select count(*)
      from public.markets
      where season_id = v_season.id
    )
  );
end;
$$;

create or replace function public.admin_delete_draft_season(
  p_operator_id uuid,
  p_season_id integer
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_season public.seasons;
  v_impact jsonb;
begin
  select *
  into v_season
  from public.seasons
  where id = p_season_id
  for update;

  if not found then
    raise exception '시즌을 찾을 수 없습니다';
  end if;
  if v_season.status <> 'DRAFT' then
    raise exception 'DRAFT 시즌만 삭제할 수 있습니다';
  end if;

  v_impact := public.get_draft_season_delete_impact(p_season_id);
  if (v_impact->>'linked_matches')::integer > 0
    or (v_impact->>'linked_markets')::integer > 0 then
    raise exception '연결된 경기 또는 마켓이 있어 DRAFT 시즌을 삭제할 수 없습니다';
  end if;

  delete from public.seasons where id = p_season_id;

  insert into public.admin_audit_logs (
    operator_id, action, target_type, target_id,
    before_state, after_state, success
  )
  values (
    p_operator_id,
    'SEASON_DRAFT_DELETE',
    'season',
    p_season_id::text,
    to_jsonb(v_season),
    v_impact,
    true
  );

  return v_impact;
end;
$$;

create or replace function public.get_season_activation_preview(
  p_season_id integer
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_season public.seasons;
  v_eligible_members integer;
begin
  select *
  into v_season
  from public.seasons
  where id = p_season_id;

  if not found then
    raise exception '시즌을 찾을 수 없습니다';
  end if;
  if v_season.status <> 'DRAFT' then
    raise exception 'DRAFT 시즌만 활성화할 수 있습니다';
  end if;

  select count(*) into v_eligible_members from public.users;

  return jsonb_build_object(
    'season_id', v_season.id,
    'season_name', v_season.name,
    'initial_grant_amount', v_season.initial_grant_amount,
    'eligible_members', v_eligible_members,
    'total_planned_grant',
      v_eligible_members * v_season.initial_grant_amount
  );
end;
$$;

create or replace function public.admin_activate_season(
  p_operator_id uuid,
  p_season_id integer
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_target public.seasons;
  v_active public.seasons;
  v_pending_count integer;
  v_preview jsonb;
  v_wallet_count integer;
  v_grant_count integer;
begin
  select *
  into v_target
  from public.seasons
  where id = p_season_id
  for update;

  if not found then
    raise exception '시즌을 찾을 수 없습니다';
  end if;
  if v_target.status <> 'DRAFT' then
    raise exception 'DRAFT 시즌만 활성화할 수 있습니다';
  end if;
  if v_target.initial_grant_amount <= 0 then
    raise exception '초기 지급액은 0보다 커야 합니다';
  end if;

  if exists (
    select 1 from public.wallets where season_id = v_target.id
  ) or exists (
    select 1
    from public.transactions
    where season_id = v_target.id and type = 'SEASON_GRANT'
  ) then
    raise exception 'DRAFT 시즌에 초기 지급 데이터가 이미 존재합니다';
  end if;

  select *
  into v_active
  from public.seasons
  where status = 'ACTIVE'
  for update;

  if found then
    select count(*)
    into v_pending_count
    from public.markets
    where season_id = v_active.id
      and status in ('OPEN', 'CLOSED');

    if v_pending_count > 0 then
      raise exception '이전 시즌에 정산되지 않은 마켓이 %개 있습니다',
        v_pending_count;
    end if;
  end if;

  v_preview := public.get_season_activation_preview(v_target.id);

  if v_active.id is not null then
    update public.seasons
    set status = 'ARCHIVED',
        end_date = coalesce(end_date, v_target.start_date - 1)
    where id = v_active.id;
  end if;

  update public.seasons
  set status = 'ACTIVE'
  where id = v_target.id;

  insert into public.wallets (
    user_id, season_id, balance, created_at, updated_at
  )
  select
    u.id,
    v_target.id,
    v_target.initial_grant_amount,
    now(),
    now()
  from public.users u;
  get diagnostics v_wallet_count = row_count;

  insert into public.transactions (
    user_id,
    season_id,
    type,
    amount,
    balance_after,
    description,
    created_at
  )
  select
    u.id,
    v_target.id,
    'SEASON_GRANT',
    v_target.initial_grant_amount,
    v_target.initial_grant_amount,
    '시즌 시작 코인 지급',
    now()
  from public.users u;
  get diagnostics v_grant_count = row_count;

  if v_wallet_count <> v_grant_count then
    raise exception '시즌 지갑과 지급 기록 수가 일치하지 않습니다';
  end if;

  insert into public.admin_audit_logs (
    operator_id, action, target_type, target_id,
    before_state, after_state, success
  )
  values (
    p_operator_id,
    'SEASON_ACTIVATE',
    'season',
    v_target.id::text,
    jsonb_build_object('target', to_jsonb(v_target), 'preview', v_preview),
    jsonb_build_object(
      'status', 'ACTIVE',
      'wallets_created', v_wallet_count,
      'grants_created', v_grant_count
    ),
    true
  );

  return v_preview || jsonb_build_object(
    'success', true,
    'users_granted', v_grant_count
  );
end;
$$;

-- from 40.sql
create or replace function public.get_season_close_readiness(
  p_season_id integer,
  p_page integer default 1,
  p_page_size integer default 20
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_season public.seasons;
  v_page integer := greatest(coalesce(p_page, 1), 1);
  v_page_size integer := least(greatest(coalesce(p_page_size, 20), 1), 1000);
  v_unsettled integer;
  v_items jsonb;
begin
  select *
  into v_season
  from public.seasons
  where id = p_season_id;

  if not found then
    raise exception '시즌을 찾을 수 없습니다';
  end if;

  select count(*)
  into v_unsettled
  from public.markets
  where season_id = p_season_id
    and status in ('OPEN', 'CLOSED');

  select coalesce(jsonb_agg(to_jsonb(rows) order by rows.game_date, rows.market_id), '[]'::jsonb)
  into v_items
  from (
    select
      m.id as market_id,
      m.status::text as market_status,
      g.id as game_id,
      g.game_date,
      g.game_status::text as game_status,
      g.home_score,
      g.away_score,
      (
        select count(distinct p.user_id)
        from public.positions p
        where p.market_id = m.id and p.quantity > 0
      )::integer as position_holder_count,
      case
        when g.game_status = 'CANCELED' then 'CANCELLATION_RECOMMENDED'
        when g.game_status = 'FINISHED'
          and g.home_score is not null
          and g.away_score is not null then 'AUTO_DECIDABLE'
        else 'MANUAL_REVIEW'
      end as classification,
      case
        when g.game_status = 'FINISHED'
          and g.home_score is not null
          and g.away_score is not null
          and g.home_score > g.away_score then 'HOME'
        when g.game_status = 'FINISHED'
          and g.home_score is not null
          and g.away_score is not null
          and g.home_score < g.away_score then 'AWAY'
        when g.game_status = 'FINISHED'
          and g.home_score is not null
          and g.away_score is not null then 'DRAW'
        else null
      end as proposed_result,
      coalesce((
        select sum(p.quantity * 100)
        from public.positions p
        where p.market_id = m.id
          and p.quantity > 0
          and p.outcome = case
            when g.game_status = 'FINISHED'
              and g.home_score > g.away_score then 'HOME'
            when g.game_status = 'FINISHED'
              and g.home_score < g.away_score then 'AWAY'
            when g.game_status = 'FINISHED' then 'DRAW'
            else ''
          end
      ), 0) as estimated_payout,
      coalesce((
        select sum(p.quantity * p.avg_entry_price)
        from public.positions p
        where p.market_id = m.id and p.quantity > 0
      ), 0) as estimated_refund,
      case
        when g.game_status = 'CANCELED' then array['CANCEL']::text[]
        when m.status = 'OPEN' then array['CLOSE', 'SETTLE', 'CANCEL']::text[]
        else array['SETTLE', 'CANCEL']::text[]
      end as eligible_actions
    from public.markets m
    join public.games g on g.id = m.game_id
    where m.season_id = p_season_id
      and m.status in ('OPEN', 'CLOSED')
    order by g.game_date, m.id
    offset (v_page - 1) * v_page_size
    limit v_page_size
  ) rows;

  return jsonb_build_object(
    'season_id', v_season.id,
    'season_name', v_season.name,
    'season_status', v_season.status,
    'status_counts', jsonb_build_object(
      'OPEN', (
        select count(*) from public.markets
        where season_id = p_season_id and status = 'OPEN'
      ),
      'CLOSED', (
        select count(*) from public.markets
        where season_id = p_season_id and status = 'CLOSED'
      ),
      'CANCELED', (
        select count(*) from public.markets
        where season_id = p_season_id and status = 'CANCELED'
      ),
      'SETTLED', (
        select count(*) from public.markets
        where season_id = p_season_id and status = 'SETTLED'
      )
    ),
    'unsettled_count', v_unsettled,
    'closure_available', v_season.status = 'ACTIVE' and v_unsettled = 0,
    'next_activation_available', v_unsettled = 0,
    'page', v_page,
    'page_size', v_page_size,
    'total_pages', greatest(ceil(v_unsettled::numeric / v_page_size)::integer, 1),
    'items', v_items
  );
end;
$$;

create or replace function public.admin_process_season_markets(
  p_operator_id uuid,
  p_season_id integer,
  p_items jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  v_season public.seasons;
  v_item jsonb;
  v_market public.markets;
  v_game public.games;
  v_market_id integer;
  v_action text;
  v_result text;
  v_rpc jsonb;
  v_before jsonb;
  v_after jsonb;
  v_results jsonb := '[]'::jsonb;
  v_before_rows jsonb := '[]'::jsonb;
  v_after_rows jsonb := '[]'::jsonb;
  v_success_count integer := 0;
  v_failure_count integer := 0;
  v_outcome_status text;
  v_message text;
begin
  select *
  into v_season
  from public.seasons
  where id = p_season_id
  for update;

  if not found then
    raise exception '시즌을 찾을 수 없습니다';
  end if;
  if v_season.status <> 'ACTIVE' then
    raise exception 'ACTIVE 시즌의 마켓만 처리할 수 있습니다';
  end if;
  if p_items is null
    or jsonb_typeof(p_items) <> 'array'
    or jsonb_array_length(p_items) = 0 then
    raise exception '처리할 마켓을 선택해주세요';
  end if;

  for v_item in select value from jsonb_array_elements(p_items)
  loop
    v_market_id := nullif(v_item->>'market_id', '')::integer;
    v_action := upper(btrim(coalesce(v_item->>'action', '')));
    v_result := upper(btrim(coalesce(v_item->>'result', '')));
    v_before := null;
    v_after := null;
    v_rpc := null;
    v_outcome_status := 'SUCCESS';
    v_message := '처리 완료';

    begin
      if v_action not in ('CLOSE', 'SETTLE', 'CANCEL') then
        raise exception '지원하지 않는 처리 작업입니다';
      end if;

      select *
      into v_market
      from public.markets
      where id = v_market_id and season_id = p_season_id
      for update;

      if not found then
        raise exception '시즌에 속한 마켓을 찾을 수 없습니다';
      end if;

      select *
      into v_game
      from public.games
      where id = v_market.game_id;

      v_before := to_jsonb(v_market);
      v_before_rows := v_before_rows || jsonb_build_array(v_before);

      if v_action = 'CLOSE' and v_market.status = 'CLOSED' then
        v_outcome_status := 'SKIPPED';
        v_message := '이미 종료된 마켓입니다';
      elsif v_action = 'SETTLE' and v_market.status = 'SETTLED' then
        v_outcome_status := 'SKIPPED';
        v_message := '이미 정산된 마켓입니다';
      elsif v_action = 'CANCEL' and v_market.status = 'CANCELED' then
        v_outcome_status := 'SKIPPED';
        v_message := '이미 취소된 마켓입니다';
      elsif v_market.status in ('SETTLED', 'CANCELED') then
        raise exception '완료된 마켓에는 다른 작업을 실행할 수 없습니다';
      elsif v_game.game_status = 'CANCELED' and v_action <> 'CANCEL' then
        raise exception '취소 경기는 CANCEL만 실행할 수 있습니다';
      elsif v_action = 'CLOSE' then
        v_rpc := public.close_market(v_market.id);
        if not coalesce((v_rpc->>'success')::boolean, false) then
          raise exception '%', coalesce(v_rpc->>'error', '마켓 종료 실패');
        end if;
      elsif v_action = 'CANCEL' then
        v_rpc := public.cancel_market(v_market.id);
        if not coalesce((v_rpc->>'success')::boolean, false) then
          raise exception '%', coalesce(v_rpc->>'error', '마켓 취소 실패');
        end if;
      else
        if v_result not in ('HOME', 'AWAY', 'DRAW') then
          if v_game.game_status = 'FINISHED'
            and v_game.home_score is not null
            and v_game.away_score is not null then
            v_result := case
              when v_game.home_score > v_game.away_score then 'HOME'
              when v_game.home_score < v_game.away_score then 'AWAY'
              else 'DRAW'
            end;
          else
            raise exception '수동 검토 마켓은 정산 결과를 선택해야 합니다';
          end if;
        end if;

        if v_market.status = 'OPEN' then
          v_rpc := public.close_market(v_market.id);
          if not coalesce((v_rpc->>'success')::boolean, false) then
            raise exception '%', coalesce(v_rpc->>'error', '마켓 종료 실패');
          end if;
        end if;

        v_rpc := public.settle_market(v_market.id, v_result);
        if not coalesce((v_rpc->>'success')::boolean, false) then
          raise exception '%', coalesce(v_rpc->>'error', '마켓 정산 실패');
        end if;
      end if;

      select to_jsonb(m)
      into v_after
      from public.markets m
      where m.id = v_market_id;
      v_after_rows := v_after_rows || jsonb_build_array(v_after);
      v_success_count := v_success_count + 1;
    exception
      when others then
        v_outcome_status := 'FAILURE';
        v_message := sqlerrm;
        select to_jsonb(m)
        into v_after
        from public.markets m
        where m.id = v_market_id;
        if v_after is not null then
          v_after_rows := v_after_rows || jsonb_build_array(v_after);
        end if;
        v_failure_count := v_failure_count + 1;
    end;

    v_results := v_results || jsonb_build_array(jsonb_build_object(
      'market_id', v_market_id,
      'action', v_action,
      'result', nullif(v_result, ''),
      'status', v_outcome_status,
      'message', v_message,
      'before', v_before,
      'after', v_after,
      'rpc_result', v_rpc
    ));
  end loop;

  insert into public.admin_audit_logs (
    operator_id, action, target_type, target_id,
    before_state, after_state, success
  )
  values (
    p_operator_id,
    'SEASON_MARKET_BULK_PROCESS',
    'season',
    p_season_id::text,
    jsonb_build_object('inputs', p_items, 'markets', v_before_rows),
    jsonb_build_object('results', v_results, 'markets', v_after_rows),
    v_failure_count = 0
  );

  return jsonb_build_object(
    'season_id', p_season_id,
    'success_count', v_success_count,
    'failure_count', v_failure_count,
    'results', v_results,
    'readiness', public.get_season_close_readiness(
      p_season_id, 1, 20
    )
  );
end;
$$;

create or replace function public.admin_close_ready_season(
  p_operator_id uuid,
  p_season_id integer
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_before public.seasons;
  v_readiness jsonb;
  v_result jsonb;
begin
  select *
  into v_before
  from public.seasons
  where id = p_season_id
  for update;

  if not found then
    raise exception '시즌을 찾을 수 없습니다';
  end if;
  if v_before.status <> 'ACTIVE' then
    raise exception 'ACTIVE 시즌만 종료할 수 있습니다';
  end if;

  v_readiness := public.get_season_close_readiness(
    p_season_id, 1, 1
  );
  if (v_readiness->>'unsettled_count')::integer <> 0 then
    raise exception '미정산 마켓이 남아 있어 시즌을 종료할 수 없습니다';
  end if;

  v_result := public.end_season(p_season_id);
  if not coalesce((v_result->>'success')::boolean, false) then
    raise exception '%', coalesce(v_result->>'error', '시즌 종료 실패');
  end if;

  insert into public.admin_audit_logs (
    operator_id, action, target_type, target_id,
    before_state, after_state, success
  )
  values (
    p_operator_id,
    'SEASON_CLOSE',
    'season',
    p_season_id::text,
    to_jsonb(v_before),
    v_result,
    true
  );

  return v_result || jsonb_build_object(
    'readiness_before_close', v_readiness
  );
end;
$$;

-- from 41.sql
create or replace function public.weekly_grant_cron_expression(
  p_weekday integer,
  p_grant_time time
)
returns text
language plpgsql
immutable
as $$
declare
  v_kst_dow integer;
  v_utc_dow integer;
  v_hour integer;
  v_minute integer;
begin
  if p_weekday not between 1 and 7 then
    raise exception '요일은 1(월)부터 7(일) 사이여야 합니다';
  end if;
  v_hour := extract(hour from p_grant_time)::integer;
  v_minute := extract(minute from p_grant_time)::integer;
  v_kst_dow := p_weekday % 7;
  v_utc_dow := (v_kst_dow - case when v_hour < 9 then 1 else 0 end + 7) % 7;
  return format(
    '%s %s * * %s',
    v_minute,
    (v_hour + 15) % 24,
    v_utc_dow
  );
end;
$$;

create or replace function public.sync_weekly_grant_cron()
returns void
language plpgsql
security definer
set search_path = public, cron
as $$
declare
  v_policy public.weekly_grant_policies;
  v_schedule text;
  v_job_id bigint;
begin
  select p.*
  into v_policy
  from public.weekly_grant_policies p
  join public.seasons s on s.id = p.season_id
  where s.status = 'ACTIVE'
  limit 1;

  if not found then
    return;
  end if;

  v_schedule := public.weekly_grant_cron_expression(
    v_policy.weekday,
    v_policy.grant_time
  );
  select jobid into v_job_id
  from cron.job
  where jobname = 'weekly_coin_distribution';

  if v_job_id is null then
    perform cron.schedule(
      'weekly_coin_distribution',
      v_schedule,
      'SELECT public.run_scheduled_weekly_grant();'
    );
    select jobid into v_job_id
    from cron.job
    where jobname = 'weekly_coin_distribution';
  end if;

  perform cron.alter_job(
    v_job_id,
    schedule := v_schedule,
    command := 'SELECT public.run_scheduled_weekly_grant();',
    active := v_policy.automatic_enabled and not v_policy.is_paused
  );
end;
$$;

create or replace function public.get_weekly_grant_status()
returns jsonb
language plpgsql
security definer
set search_path = public, cron
as $$
declare
  v_policy public.weekly_grant_policies;
  v_season public.seasons;
  v_recipient_count integer;
  v_job cron.job;
  v_runs jsonb;
begin
  select * into v_season
  from public.seasons where status = 'ACTIVE' limit 1;
  if not found then
    raise exception '활성 시즌이 없습니다';
  end if;

  select * into v_policy
  from public.weekly_grant_policies
  where season_id = v_season.id;
  if not found then
    raise exception '주간 지급 정책을 찾을 수 없습니다';
  end if;

  select count(*) into v_recipient_count from public.users;
  select * into v_job
  from cron.job where jobname = 'weekly_coin_distribution';
  select coalesce(jsonb_agg(to_jsonb(r) order by r.started_at desc), '[]'::jsonb)
  into v_runs
  from (
    select id, round_key, source, status, scheduled_for,
      recipient_count, total_payout, failure_count,
      error_message, started_at, completed_at
    from public.weekly_grant_runs
    where season_id = v_season.id
    order by started_at desc
    limit 10
  ) r;

  return jsonb_build_object(
    'season_id', v_season.id,
    'season_name', v_season.name,
    'amount', v_policy.amount,
    'weekday', v_policy.weekday,
    'grant_time', to_char(v_policy.grant_time, 'HH24:MI'),
    'automatic_enabled', v_policy.automatic_enabled,
    'is_paused', v_policy.is_paused,
    'cron_expression', public.weekly_grant_cron_expression(
      v_policy.weekday, v_policy.grant_time
    ),
    'cron_active', coalesce(v_job.active, false),
    'next_run', case
      when v_policy.automatic_enabled and not v_policy.is_paused
      then public.weekly_grant_next_run(v_policy.weekday, v_policy.grant_time)
      else null
    end,
    'expected_recipient_count', v_recipient_count,
    'estimated_total_payout', v_recipient_count * v_policy.amount,
    'recent_runs', v_runs
  );
end;
$$;

create or replace function public.admin_update_weekly_grant_policy(
  p_operator_id uuid,
  p_amount numeric,
  p_weekday integer,
  p_grant_time time,
  p_automatic_enabled boolean
)
returns jsonb
language plpgsql
security definer
set search_path = public, cron
as $$
declare
  v_season public.seasons;
  v_before public.weekly_grant_policies;
  v_after public.weekly_grant_policies;
begin
  if p_amount is null or p_amount <= 0 then
    raise exception '지급액은 0보다 커야 합니다';
  end if;
  perform public.weekly_grant_cron_expression(p_weekday, p_grant_time);
  select * into v_season from public.seasons where status = 'ACTIVE' limit 1;
  if not found then raise exception '활성 시즌이 없습니다'; end if;

  select * into v_before
  from public.weekly_grant_policies
  where season_id = v_season.id
  for update;

  insert into public.weekly_grant_policies (
    season_id, amount, weekday, grant_time, automatic_enabled, is_paused
  )
  values (
    v_season.id, p_amount, p_weekday, p_grant_time,
    p_automatic_enabled, false
  )
  on conflict (season_id) do update
  set amount = excluded.amount,
      weekday = excluded.weekday,
      grant_time = excluded.grant_time,
      automatic_enabled = excluded.automatic_enabled,
      updated_at = now()
  returning * into v_after;

  perform public.sync_weekly_grant_cron();
  insert into public.admin_audit_logs (
    operator_id, action, target_type, target_id,
    before_state, after_state, success
  ) values (
    p_operator_id, 'WEEKLY_GRANT_POLICY_UPDATE', 'season',
    v_season.id::text, to_jsonb(v_before), to_jsonb(v_after), true
  );
  return public.get_weekly_grant_status();
end;
$$;

create or replace function public.admin_set_weekly_grant_pause(
  p_operator_id uuid,
  p_paused boolean
)
returns jsonb
language plpgsql
security definer
set search_path = public, cron
as $$
declare
  v_policy public.weekly_grant_policies;
begin
  update public.weekly_grant_policies p
  set is_paused = p_paused, updated_at = now()
  from public.seasons s
  where s.id = p.season_id and s.status = 'ACTIVE'
  returning p.* into v_policy;
  if not found then raise exception '주간 지급 정책을 찾을 수 없습니다'; end if;
  perform public.sync_weekly_grant_cron();
  insert into public.admin_audit_logs (
    operator_id, action, target_type, target_id, after_state, success
  ) values (
    p_operator_id,
    case when p_paused then 'WEEKLY_GRANT_PAUSE' else 'WEEKLY_GRANT_RESUME' end,
    'season', v_policy.season_id::text, to_jsonb(v_policy), true
  );
  return public.get_weekly_grant_status();
end;
$$;

create or replace function public.run_weekly_grant_round(
  p_operator_id uuid,
  p_round_key text,
  p_source text,
  p_scheduled_for timestamptz default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_policy public.weekly_grant_policies;
  v_season public.seasons;
  v_run public.weekly_grant_runs;
  v_recipient_count integer;
  v_total numeric;
begin
  if btrim(coalesce(p_round_key, '')) = '' then
    raise exception '지급 라운드를 입력해주세요';
  end if;
  if upper(p_source) not in ('AUTO', 'MANUAL') then
    raise exception '지급 실행 구분이 올바르지 않습니다';
  end if;
  select * into v_season from public.seasons where status = 'ACTIVE' limit 1;
  if not found then raise exception '활성 시즌이 없습니다'; end if;
  select * into v_policy from public.weekly_grant_policies
  where season_id = v_season.id;

  insert into public.weekly_grant_runs (
    season_id, round_key, source, status, scheduled_for, initiated_by
  ) values (
    v_season.id, btrim(p_round_key), upper(p_source), 'RUNNING',
    p_scheduled_for, p_operator_id
  )
  on conflict (season_id, round_key) do nothing;

  select * into v_run from public.weekly_grant_runs
  where season_id = v_season.id and round_key = btrim(p_round_key)
  for update;

  if v_run.status = 'SUCCESS' then
    return jsonb_build_object(
      'status', 'SKIPPED', 'run_id', v_run.id,
      'round_key', v_run.round_key, 'message', '이미 지급된 라운드입니다'
    );
  end if;
  if upper(p_source) = 'AUTO'
    and (not v_policy.automatic_enabled or v_policy.is_paused) then
    update public.weekly_grant_runs
    set status = 'SKIPPED', completed_at = now(),
        error_message = '자동 지급이 일시정지되었습니다'
    where id = v_run.id;
    return jsonb_build_object(
      'status', 'SKIPPED', 'run_id', v_run.id,
      'round_key', v_run.round_key,
      'message', '자동 지급이 일시정지되었습니다'
    );
  end if;

  update public.weekly_grant_runs
  set source = upper(p_source), status = 'RUNNING',
      initiated_by = p_operator_id, started_at = now(),
      completed_at = null, error_message = null
  where id = v_run.id;

  begin
    insert into public.wallets (user_id, season_id, balance)
    select id, v_season.id, 0 from public.users
    on conflict (user_id, season_id) do nothing;

    with updated as (
      update public.wallets w
      set balance = w.balance + v_policy.amount, updated_at = now()
      where w.season_id = v_season.id
      returning w.user_id, w.balance
    ), recipient_rows as (
      insert into public.weekly_grant_run_recipients (
        run_id, user_id, amount, balance_after
      )
      select v_run.id, user_id, v_policy.amount, balance from updated
      returning user_id, balance_after
    ), transaction_rows as (
      insert into public.transactions (
        user_id, type, amount, balance_after, reference_id,
        description, season_id
      )
      select user_id, 'WEEKLY_GRANT', v_policy.amount, balance_after,
        v_run.id, '주간 코인 지급 ' || btrim(p_round_key), v_season.id
      from recipient_rows
      returning user_id
    )
    select count(*), count(*) * v_policy.amount
    into v_recipient_count, v_total
    from transaction_rows;

    update public.weekly_grant_runs
    set status = 'SUCCESS', recipient_count = v_recipient_count,
        total_payout = v_total, failure_count = 0, completed_at = now()
    where id = v_run.id;
  exception when others then
    update public.weekly_grant_runs
    set status = 'FAILURE', failure_count = 1,
        error_message = sqlerrm, completed_at = now()
    where id = v_run.id;
    insert into public.admin_audit_logs (
      operator_id, action, target_type, target_id, after_state, success,
      error_message
    ) values (
      p_operator_id, 'WEEKLY_GRANT_' || upper(p_source) || '_RUN',
      'weekly_grant_run', v_run.id::text,
      jsonb_build_object('round_key', p_round_key, 'status', 'FAILURE'),
      false, sqlerrm
    );
    return jsonb_build_object(
      'status', 'FAILURE', 'run_id', v_run.id,
      'round_key', p_round_key, 'error', sqlerrm
    );
  end;

  insert into public.admin_audit_logs (
    operator_id, action, target_type, target_id, after_state, success
  ) values (
    p_operator_id, 'WEEKLY_GRANT_' || upper(p_source) || '_RUN',
    'weekly_grant_run', v_run.id::text,
    jsonb_build_object(
      'round_key', p_round_key, 'status', 'SUCCESS',
      'recipient_count', v_recipient_count, 'total_payout', v_total
    ), true
  );
  return jsonb_build_object(
    'status', 'SUCCESS', 'run_id', v_run.id,
    'round_key', p_round_key, 'recipient_count', v_recipient_count,
    'total_payout', v_total
  );
end;
$$;

-- from 42.sql
create or replace function public.get_kbo_sync_status()
returns jsonb language sql security definer set search_path=public,cron as $$
select jsonb_build_object(
 'jobs',(select jsonb_agg(jsonb_build_object(
   'mode',j.mode,'status',j.status,'schedule_kst',to_char(j.schedule_kst,'HH24:MI'),
   'enabled',j.enabled,'next_run',case when j.enabled and j.status='ACTIVE' then now()+interval '1 hour' end,
   'recent_runs',(select coalesce(jsonb_agg(to_jsonb(r) order by r.created_at desc),'[]') from
      (select * from public.kbo_sync_runs where mode=j.mode order by created_at desc limit 5) r)
 ) order by j.mode) from public.kbo_sync_jobs j),
 'secret', (select jsonb_build_object('configured',configured,'last_rotated_at',last_rotated_at) from public.kbo_sync_secret_status where id)
); $$;

create or replace function public.admin_update_kbo_sync_job(p_operator_id uuid,p_mode text,p_schedule_kst time,p_enabled boolean,p_paused boolean)
returns jsonb language plpgsql security definer set search_path=public as $$
begin
 update public.kbo_sync_jobs set schedule_kst=p_schedule_kst,enabled=p_enabled,
 status=case when not p_enabled then 'DISABLED' when p_paused then 'PAUSED' else 'ACTIVE' end,updated_at=now()
 where mode=upper(p_mode);
 if not found then raise exception '동기화 작업을 찾을 수 없습니다'; end if;
 insert into public.admin_audit_logs(operator_id,action,target_type,target_id,after_state,success)
 values(p_operator_id,'KBO_SYNC_JOB_UPDATE','kbo_sync_job',upper(p_mode),
 jsonb_build_object('mode',upper(p_mode),'schedule_kst',p_schedule_kst,'enabled',p_enabled,'paused',p_paused),true);
 return public.get_kbo_sync_status();
end; $$;

create or replace function public.admin_run_kbo_sync(p_operator_id uuid,p_mode text,p_target_date date,p_initial_price numeric,p_retry_run_id integer default null)
returns jsonb language plpgsql security definer set search_path=public as $$
declare v_job public.kbo_sync_jobs; v_secret boolean; v_attempt integer:=1; v_run public.kbo_sync_runs; v_updated integer;
begin
 select * into v_job from public.kbo_sync_jobs where mode=upper(p_mode);
 if not found then raise exception '동기화 작업을 찾을 수 없습니다'; end if;
 if p_initial_price<=0 then raise exception '초기 가격은 0보다 커야 합니다'; end if;
 select coalesce(max(attempt),0)+1 into v_attempt
 from public.kbo_sync_runs
 where mode=v_job.mode and target_date=p_target_date and initial_price=p_initial_price;
 if p_retry_run_id is not null then
   perform 1 from public.kbo_sync_runs
   where id=p_retry_run_id and mode=v_job.mode
     and target_date=p_target_date and initial_price=p_initial_price;
   if not found then raise exception '재시도할 실행을 찾을 수 없습니다'; end if;
 end if;
 select configured into v_secret from public.kbo_sync_secret_status where id;
 select count(*) into v_updated from public.games where game_date=p_target_date;
 insert into public.kbo_sync_runs(mode,target_date,initial_price,attempt,status,error_code,
 matches_updated,skipped_items,error_count,initiated_by)
 values(v_job.mode,p_target_date,p_initial_price,v_attempt,
 case when v_secret then 'SUCCESS' else 'FAILURE' end,
 case when v_secret then null else 'MISSING_VAULT_SECRET' end,
 case when v_secret then v_updated else 0 end,
 case when v_secret then v_updated else 0 end,
 case when v_secret then 0 else 1 end,p_operator_id) returning * into v_run;
 insert into public.admin_audit_logs(operator_id,action,target_type,target_id,after_state,success,error_message)
 values(p_operator_id,case when p_retry_run_id is null then 'KBO_SYNC_MANUAL_RUN' else 'KBO_SYNC_RETRY' end,
 'kbo_sync_run',v_run.id::text,to_jsonb(v_run),v_run.status='SUCCESS',
 case when v_run.status='FAILURE' then v_run.error_code end);
 return to_jsonb(v_run);
end; $$;

-- from 43.sql
create or replace function public.admin_adjust_wallet(p_operator_id uuid,p_user_id uuid,p_season_id integer,p_amount numeric,p_reason text,p_internal_memo text)
returns jsonb language plpgsql security definer set search_path=public as $$
declare w public.wallets; n numeric; t public.transactions;
begin
 if p_amount=0 then raise exception '금액은 0이 아니어야 합니다'; end if;
 if btrim(coalesce(p_reason,''))='' or btrim(coalesce(p_internal_memo,''))='' then raise exception '사유와 내부 메모를 입력해주세요'; end if;
 select * into w from public.wallets where user_id=p_user_id and season_id=p_season_id for update;
 if not found then raise exception '지갑을 찾을 수 없습니다'; end if;
 n:=w.balance+p_amount; if n<0 then raise exception '차감 후 잔액은 음수가 될 수 없습니다'; end if;
 update public.wallets set balance=n,updated_at=now() where id=w.id;
 insert into public.transactions(user_id,season_id,type,amount,balance_after,reason,internal_memo,admin_operator_id,description)
 values(p_user_id,p_season_id,case when p_amount>0 then 'ADMIN_GRANT' else 'ADMIN_DEDUCTION' end,p_amount,n,p_reason,p_internal_memo,p_operator_id,'관리자 지갑 조정') returning * into t;
 insert into public.admin_audit_logs(operator_id,action,target_type,target_id,before_state,after_state,success)
 values(p_operator_id,'WALLET_ADJUST','wallet',w.id::text,jsonb_build_object('balance',w.balance,'reason',p_reason),jsonb_build_object('balance',n,'transaction_id',t.id),true);
 return jsonb_build_object('transaction_id',t.id,'before_balance',w.balance,'after_balance',n);
end; $$;

create or replace function public.admin_cancel_admin_grant(p_operator_id uuid,p_transaction_id integer,p_reason text,p_internal_memo text)
returns jsonb language plpgsql security definer set search_path=public as $$
declare o public.transactions; w public.wallets; t public.transactions; n numeric;
begin
 select * into o from public.transactions where id=p_transaction_id and type='ADMIN_GRANT' for update;
 if not found then raise exception '취소할 관리자 지급을 찾을 수 없습니다'; end if;
 if exists(select 1 from public.transactions where reverses_transaction_id=o.id) then raise exception '이미 취소된 관리자 지급입니다'; end if;
 select * into w from public.wallets where user_id=o.user_id and season_id=o.season_id for update;
 n:=w.balance-o.amount; if n<0 then raise exception '취소 후 잔액은 음수가 될 수 없습니다'; end if;
 update public.wallets set balance=n,updated_at=now() where id=w.id;
 insert into public.transactions(user_id,season_id,type,amount,balance_after,reason,internal_memo,admin_operator_id,reverses_transaction_id,description)
 values(o.user_id,o.season_id,'ADMIN_REVERSAL',-o.amount,n,p_reason,p_internal_memo,p_operator_id,o.id,'관리자 지급 취소') returning * into t;
 insert into public.admin_audit_logs(operator_id,action,target_type,target_id,before_state,after_state,success)
 values(p_operator_id,'WALLET_GRANT_CANCEL','transaction',o.id::text,to_jsonb(o),to_jsonb(t),true);
 return jsonb_build_object('transaction_id',t.id,'reverses_transaction_id',o.id,'after_balance',n);
end; $$;

create or replace function public.get_wallet_diagnostics(p_user_id uuid,p_season_id integer)
returns jsonb language sql security definer set search_path=public as $$
select jsonb_build_object('wallet',to_jsonb(w),'ledger_sum',coalesce((select sum(amount) from transactions where user_id=p_user_id and season_id=p_season_id),0),
'mismatch',w.balance<>coalesce((select sum(amount) from transactions where user_id=p_user_id and season_id=p_season_id),0),
'entries',coalesce((select jsonb_agg(to_jsonb(t) order by t.created_at desc) from (select * from transactions where user_id=p_user_id and season_id=p_season_id order by created_at desc limit 100)t),'[]')) from wallets w where user_id=p_user_id and season_id=p_season_id; $$;

create or replace function public.admin_wallet_recovery_json(p_input jsonb)
returns jsonb language plpgsql security definer set search_path=public as $$
begin
 if p_input->>'action'='adjust' then
  return public.admin_adjust_wallet(
   nullif(p_input->>'operator_id','undefined')::uuid,
   nullif(p_input->>'user_id','undefined')::uuid,
   (p_input->>'season_id')::integer,(p_input->>'amount')::numeric,
   p_input->>'reason',p_input->>'memo');
 end if;
 return public.admin_cancel_admin_grant(
  nullif(p_input->>'operator_id','undefined')::uuid,
  (p_input->>'transaction_id')::integer,p_input->>'reason',p_input->>'memo');
end; $$;

-- from 44.sql
create or replace function public.preview_match_correction(p_game_id integer)returns jsonb language sql security definer set search_path=public as $$
select jsonb_build_object('game',to_jsonb(g),'market',to_jsonb(m),'order_count',(select count(*) from orders where market_id=m.id),'position_count',(select count(*) from positions where market_id=m.id),'deletable',m.id is null or(not exists(select 1 from orders where market_id=m.id)and not exists(select 1 from positions where market_id=m.id))) from games g left join markets m on m.game_id=g.id where g.id=p_game_id;$$;

create or replace function public.admin_correct_match(p_operator_id uuid,p_game_id integer,p_action text,p_home_team_id integer,p_away_team_id integer,p_game_date date,p_game_time time,p_initial_price numeric,p_b numeric)
returns jsonb language plpgsql security definer set search_path=public as $$declare g games;m markets;impact jsonb;begin select * into g from games where id=p_game_id for update;if not found then raise exception '경기를 찾을 수 없습니다';end if;select * into m from markets where game_id=g.id for update;impact:=preview_match_correction(g.id);if m.status='SETTLED' then raise exception '정산 후 복구는 별도 워크플로우를 사용해주세요';end if;if m.id is not null and(exists(select 1 from orders where market_id=m.id)or exists(select 1 from positions where market_id=m.id))then raise exception '주문 또는 포지션이 있어 삭제/초기가 변경이 차단됩니다';end if;if upper(p_action)='DELETE'then if m.id is not null then delete from markets where id=m.id;end if;delete from games where id=g.id;elsif upper(p_action)='RECREATE'then if exists(select 1 from games where id<>g.id and game_date=p_game_date and home_team_id=p_home_team_id and away_team_id=p_away_team_id)then raise exception '중복 경기가 존재합니다. 병합 또는 취소를 선택해주세요';end if;if m.id is not null then delete from markets where id=m.id;end if;update games set home_team_id=p_home_team_id,away_team_id=p_away_team_id,game_date=p_game_date,game_time=p_game_time where id=g.id;insert into markets(game_id,b,status,season_id)values(g.id,p_b,'OPEN',(select id from seasons where status='ACTIVE'));else update games set home_team_id=p_home_team_id,away_team_id=p_away_team_id,game_date=p_game_date,game_time=p_game_time where id=g.id;end if;insert into admin_audit_logs(operator_id,action,target_type,target_id,before_state,after_state,success)values(p_operator_id,'MATCH_CORRECTION','game',p_game_id::text,impact,preview_match_correction(p_game_id),true);return impact;end;$$;

-- from 45.sql
create or replace function public.preview_settlement_recovery(p_market_id integer)returns jsonb language sql security definer set search_path=public as $$select jsonb_build_object('event',to_jsonb(e),'shortages',coalesce((select jsonb_agg(jsonb_build_object('user_id',x.user_id,'payout',x.amount,'balance',w.balance,'shortage',greatest(x.amount-w.balance,0)))from jsonb_to_recordset(e.payout_snapshot)as x(transaction_id integer,user_id uuid,amount numeric)join wallets w on w.user_id=x.user_id and w.season_id=(select season_id from markets where id=e.market_id)where w.balance<x.amount),'[]'))from settlement_events e where market_id=p_market_id;$$;

create or replace function public.admin_recover_settlement(p_operator_id uuid,p_market_id integer,p_correct_result text,p_reason text)returns jsonb language plpgsql security definer set search_path=public as $$declare e settlement_events;r settlement_recoveries;x record;w wallets;p numeric;begin if btrim(coalesce(p_reason,''))=''then raise exception '복구 사유를 입력해주세요';end if;select*into e from settlement_events where market_id=p_market_id for update;if not found then raise exception '정산 이벤트를 찾을 수 없습니다';end if;if exists(select 1 from settlement_recoveries where event_id=e.id)then raise exception '이미 복구된 정산입니다';end if;for x in select*from jsonb_to_recordset(e.payout_snapshot)as q(transaction_id integer,user_id uuid,amount numeric)loop select*into w from wallets where user_id=x.user_id and season_id=(select season_id from markets where id=p_market_id)for update;if w.balance<x.amount then raise exception '보상 차감 잔액이 부족한 사용자가 있습니다';end if;update wallets set balance=balance-x.amount where id=w.id;insert into transactions(user_id,season_id,type,amount,balance_after,reference_id,description)values(x.user_id,w.season_id,'SETTLEMENT_REVERSAL',-x.amount,w.balance-x.amount,x.transaction_id,'정산 취소 보상');end loop;insert into settlement_recoveries(event_id,correct_result,reason,operator_id,status)values(e.id,p_correct_result,p_reason,p_operator_id,'SUCCESS')returning*into r;for x in select user_id,quantity from jsonb_to_recordset(e.position_snapshot)as q(user_id uuid,outcome text,quantity numeric)where outcome=p_correct_result loop p:=x.quantity*100;update wallets set balance=balance+p where user_id=x.user_id and season_id=(select season_id from markets where id=p_market_id)returning*into w;insert into transactions(user_id,season_id,type,amount,balance_after,reference_id,description)values(x.user_id,w.season_id,'SETTLEMENT_CORRECTION',p,w.balance,r.id,'정산 재처리 - '||p_correct_result);end loop;insert into admin_audit_logs(operator_id,action,target_type,target_id,before_state,after_state,success)values(p_operator_id,'SETTLEMENT_RECOVERY','market',p_market_id::text,to_jsonb(e),to_jsonb(r),true);return to_jsonb(r);end;$$;

-- from 47.sql
create or replace function public.preview_season_incident(p_season_id integer)returns jsonb language plpgsql security definer set search_path=public as $$declare n seasons;p seasons;begin select*into n from seasons where id=p_season_id;select*into p from seasons where status='ARCHIVED' and id<>n.id order by end_date desc nulls last limit 1;return jsonb_build_object('new_season',to_jsonb(n),'previous_season',to_jsonb(p),'counts',jsonb_build_object('wallets',(select count(*)from wallets where season_id=n.id),'orders',(select count(*)from orders where season_id=n.id),'positions',(select count(*)from positions where season_id=n.id),'markets',(select count(*)from markets where season_id=n.id),'transactions',(select count(*)from transactions where season_id=n.id)),'automatic_possible',not exists(select 1 from orders where season_id=n.id)and not exists(select 1 from transactions where season_id=n.id and type='SETTLEMENT'),'reason',case when exists(select 1 from orders where season_id=n.id)then'신규 시즌 주문 존재'when exists(select 1 from transactions where season_id=n.id and type='SETTLEMENT')then'신규 시즌 정산 존재'end);end;$$;

create or replace function public.admin_recover_season_incident(p_operator_id uuid,p_season_id integer,p_reason text)returns jsonb language plpgsql security definer set search_path=public as $$declare v jsonb;n seasons;p seasons;g record;w wallets;before jsonb;after jsonb;begin if btrim(coalesce(p_reason,''))=''then raise exception'복구 사유를 입력해주세요';end if;v:=preview_season_incident(p_season_id);if not(v->>'automatic_possible')::boolean then raise exception'자동 복구가 불가능합니다';end if;select*into n from seasons where id=p_season_id and status='ACTIVE'for update;select*into p from seasons where id=(v->'previous_season'->>'id')::integer for update;before:=jsonb_build_object('new',to_jsonb(n),'previous',to_jsonb(p));for g in select*from transactions where season_id=n.id and type='SEASON_GRANT'loop select*into w from wallets where user_id=g.user_id and season_id=n.id for update;if w.balance<g.amount then raise exception'시즌 지급 보상 차감 잔액 부족';end if;update wallets set balance=balance-g.amount where id=w.id;insert into transactions(user_id,season_id,type,amount,balance_after,reference_id,description)values(g.user_id,n.id,'SEASON_GRANT_REVERSAL',-g.amount,w.balance-g.amount,g.id,'시즌 활성화 취소 보상');end loop;update seasons set status='DRAFT'where id=n.id;update seasons set status='ACTIVE',end_date=null where id=p.id;after:=jsonb_build_object('new',(select to_jsonb(s)from seasons s where id=n.id),'previous',(select to_jsonb(s)from seasons s where id=p.id));insert into season_incidents(new_season_id,previous_season_id,reason,operator_id,before_state,after_state)values(n.id,p.id,p_reason,p_operator_id,before,after);insert into admin_audit_logs(operator_id,action,target_type,target_id,before_state,after_state,success)values(p_operator_id,'SEASON_INCIDENT_RECOVERY','season',n.id::text,before,after,true);if(select count(*)from seasons where status='ACTIVE')<>1 then raise exception'ACTIVE 시즌은 정확히 하나여야 합니다';end if;return after;end;$$;


do $$
declare
  r record;
begin
  for r in
    select p.oid::regprocedure as sig
    from pg_proc p
    join pg_namespace n on n.oid = p.pronamespace
    where n.nspname = 'public'
      and p.proname in (
        'require_admin_operator',
        'admin_write_audit','admin_apply_game_data',
        'admin_upsert_member','admin_bulk_upsert_members',
        'admin_member_impact','admin_set_member_active','admin_repair_member_wallet',
        'admin_upsert_team','admin_upsert_team_alias','resolve_team_mappings',
        'admin_approve_team_mapping','get_team_merge_impact','admin_merge_teams',
        'assert_valid_season_draft','admin_create_draft_season','admin_update_draft_season',
        'get_draft_season_delete_impact','admin_delete_draft_season',
        'get_season_activation_preview','admin_activate_season',
        'get_season_close_readiness','admin_process_season_markets','admin_close_ready_season',
        'weekly_grant_cron_expression','sync_weekly_grant_cron','get_weekly_grant_status',
        'admin_update_weekly_grant_policy','admin_set_weekly_grant_pause','run_weekly_grant_round',
        'get_kbo_sync_status','admin_update_kbo_sync_job','admin_run_kbo_sync',
        'admin_adjust_wallet','admin_cancel_admin_grant','get_wallet_diagnostics',
        'admin_wallet_recovery_json',
        'preview_match_correction','admin_correct_match',
        'preview_settlement_recovery','admin_recover_settlement',
        'preview_season_incident','admin_recover_season_incident'
      )
  loop
    execute format('grant execute on function %s to anon, authenticated, service_role', r.sig);
  end loop;
end;
$$;
