-- Issue #36: server-authorized operator accounts, sessions, and audit trail.

do $$
begin
  create type public.admin_role as enum ('OWNER', 'OPERATOR', 'VIEWER');
exception
  when duplicate_object then null;
end;
$$;

create table if not exists public.admin_operators (
  id uuid primary key default gen_random_uuid(),
  username text not null,
  display_name text not null,
  role public.admin_role not null default 'VIEWER',
  password_hash text not null,
  is_active boolean not null default true,
  must_change_password boolean not null default true,
  created_by uuid references public.admin_operators(id) on delete set null,
  last_login_at timestamptz,
  password_changed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint admin_operators_username_format
    check (username = lower(username) and username ~ '^[a-z0-9._-]{3,50}$')
);

create unique index if not exists admin_operators_username_lower_key
  on public.admin_operators (lower(username));

create table if not exists public.admin_sessions (
  id uuid primary key default gen_random_uuid(),
  operator_id uuid not null
    references public.admin_operators(id) on delete cascade,
  token_hash text not null unique,
  expires_at timestamptz not null,
  reauthenticated_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  revoked_at timestamptz,
  created_at timestamptz not null default now()
);

create index if not exists admin_sessions_operator_active_idx
  on public.admin_sessions (operator_id, expires_at)
  where revoked_at is null;

create table if not exists public.admin_audit_logs (
  id bigint generated by default as identity primary key,
  request_id uuid not null default gen_random_uuid(),
  operator_id uuid references public.admin_operators(id) on delete set null,
  action text not null,
  target_type text,
  target_id text,
  before_state jsonb,
  after_state jsonb,
  success boolean not null,
  error_message text,
  ip_address inet,
  user_agent text,
  created_at timestamptz not null default now()
);

create index if not exists admin_audit_logs_operator_created_idx
  on public.admin_audit_logs (operator_id, created_at desc);

create index if not exists admin_audit_logs_action_created_idx
  on public.admin_audit_logs (action, created_at desc);

drop trigger if exists trg_admin_operators_set_updated_at
  on public.admin_operators;
create trigger trg_admin_operators_set_updated_at
before update on public.admin_operators
for each row execute function public.set_updated_at();

alter table public.admin_operators enable row level security;
alter table public.admin_sessions enable row level security;
alter table public.admin_audit_logs enable row level security;

revoke all on public.admin_operators from public, anon, authenticated;
revoke all on public.admin_sessions from public, anon, authenticated;
revoke all on public.admin_audit_logs from public, anon, authenticated;
grant select, insert, update, delete on public.admin_operators to service_role;
grant select, insert, update, delete on public.admin_sessions to service_role;
grant select, insert on public.admin_audit_logs to service_role;
grant usage, select on sequence public.admin_audit_logs_id_seq to service_role;

revoke execute on function public.create_season(text, date, date)
  from public, anon, authenticated;
revoke execute on function public.activate_season(integer)
  from public, anon, authenticated;
revoke execute on function public.end_season(integer)
  from public, anon, authenticated;
revoke execute on function public.create_market(
  integer,
  numeric,
  numeric,
  numeric
)
  from public, anon, authenticated;
revoke execute on function public.settle_market(integer, text)
  from public, anon, authenticated;
revoke execute on function public.close_market(integer)
  from public, anon, authenticated;
revoke execute on function public.cancel_market(integer)
  from public, anon, authenticated;
revoke execute on function public.set_liquidity_b(numeric)
  from public, anon, authenticated;
revoke execute on function public.distribute_weekly_coins(numeric)
  from public, anon, authenticated;
revoke execute on function public.admin_grant_coins(uuid, numeric)
  from public, anon, authenticated;
revoke execute on function public.admin_reset_password(bigint)
  from public, anon, authenticated;
revoke execute on function public.get_weekly_coin_cron_status()
  from public, anon, authenticated;

grant execute on function public.create_season(text, date, date)
  to service_role;
grant execute on function public.activate_season(integer)
  to service_role;
grant execute on function public.end_season(integer)
  to service_role;
grant execute on function public.create_market(
  integer,
  numeric,
  numeric,
  numeric
)
  to service_role;
grant execute on function public.settle_market(integer, text)
  to service_role;
grant execute on function public.close_market(integer)
  to service_role;
grant execute on function public.cancel_market(integer)
  to service_role;
grant execute on function public.set_liquidity_b(numeric)
  to service_role;
grant execute on function public.distribute_weekly_coins(numeric)
  to service_role;
grant execute on function public.admin_grant_coins(uuid, numeric)
  to service_role;
grant execute on function public.admin_reset_password(bigint)
  to service_role;
grant execute on function public.get_weekly_coin_cron_status()
  to service_role;

revoke insert, update, delete on public.games
  from anon, authenticated;
revoke insert, update, delete on public.teams
  from anon, authenticated;
grant select on public.games, public.teams to anon, authenticated;
grant select, insert, update, delete on public.games, public.teams
  to service_role;
grant all privileges on all tables in schema public to service_role;
grant all privileges on all sequences in schema public to service_role;

create or replace function public.admin_write_audit(
  p_operator_id uuid,
  p_action text,
  p_target_type text,
  p_target_id text,
  p_before_state jsonb,
  p_after_state jsonb,
  p_success boolean,
  p_error_message text,
  p_ip_address inet,
  p_user_agent text
)
returns void
language sql
security definer
set search_path = public
as $$
  insert into public.admin_audit_logs (
    operator_id,
    action,
    target_type,
    target_id,
    before_state,
    after_state,
    success,
    error_message,
    ip_address,
    user_agent
  )
  values (
    p_operator_id,
    p_action,
    p_target_type,
    p_target_id,
    p_before_state,
    p_after_state,
    p_success,
    p_error_message,
    p_ip_address,
    p_user_agent
  );
$$;

create or replace function public.admin_execute_rpc(
  p_operator_id uuid,
  p_action text,
  p_args jsonb,
  p_ip_address inet,
  p_user_agent text
)
returns jsonb
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  v_result jsonb;
  v_error text;
begin
  begin
    if not exists (
      select 1
      from public.admin_operators
      where id = p_operator_id
        and is_active
        and not must_change_password
        and role in ('OWNER', 'OPERATOR')
    ) then
      raise exception '관리자 변경 권한이 없습니다';
    end if;

    case p_action
      when 'create_season' then
        v_result := public.create_season(
          p_args ->> 'p_name',
          (p_args ->> 'p_start_date')::date,
          (p_args ->> 'p_end_date')::date
        );
      when 'activate_season' then
        v_result := public.activate_season(
          (p_args ->> 'p_season_id')::integer
        );
      when 'end_season' then
        v_result := public.end_season(
          (p_args ->> 'p_season_id')::integer
        );
      when 'create_market' then
        v_result := public.create_market(
          (p_args ->> 'p_game_id')::integer,
          (p_args ->> 'p_initial_home')::numeric,
          (p_args ->> 'p_initial_away')::numeric,
          (p_args ->> 'p_initial_draw')::numeric
        );
      when 'settle_market' then
        v_result := public.settle_market(
          (p_args ->> 'p_market_id')::integer,
          p_args ->> 'p_result'
        );
      when 'close_market' then
        v_result := public.close_market(
          (p_args ->> 'p_market_id')::integer
        );
      when 'cancel_market' then
        v_result := public.cancel_market(
          (p_args ->> 'p_market_id')::integer
        );
      when 'set_liquidity_b' then
        v_result := public.set_liquidity_b(
          (p_args ->> 'p_b')::numeric
        );
      when 'distribute_weekly_coins' then
        v_result := public.distribute_weekly_coins(
          (p_args ->> 'p_amount')::numeric
        );
      when 'admin_grant_coins' then
        v_result := public.admin_grant_coins(
          (p_args ->> 'p_user_id')::uuid,
          (p_args ->> 'p_amount')::numeric
        );
      when 'admin_reset_password' then
        v_result := public.admin_reset_password(
          (p_args ->> 'p_student_number')::bigint
        );
      when 'get_weekly_coin_cron_status' then
        v_result := public.get_weekly_coin_cron_status();
      else
        raise exception '지원하지 않는 관리자 작업입니다: %', p_action;
    end case;
  exception
    when others then
      get stacked diagnostics v_error = message_text;
      perform public.admin_write_audit(
        p_operator_id,
        'ADMIN_RPC_' || upper(p_action),
        'rpc',
        p_action,
        jsonb_build_object('args', p_args),
        null,
        false,
        v_error,
        p_ip_address,
        p_user_agent
      );
      return jsonb_build_object(
        'success', false,
        'error', v_error
      );
  end;

  perform public.admin_write_audit(
    p_operator_id,
    'ADMIN_RPC_' || upper(p_action),
    'rpc',
    p_action,
    jsonb_build_object('args', p_args),
    jsonb_build_object('result', v_result),
    true,
    null,
    p_ip_address,
    p_user_agent
  );

  return jsonb_build_object(
    'success', true,
    'data', v_result
  );
end;
$$;

create or replace function public.admin_apply_game_data(
  p_operator_id uuid,
  p_payload jsonb,
  p_ip_address inet,
  p_user_agent text
)
returns jsonb
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  v_action text := p_payload ->> 'action';
  v_before jsonb;
  v_after jsonb;
  v_error text;
  v_game jsonb;
  v_game_id integer;
  v_target_date date;
  v_keep_ids integer[];
  v_inserted_ids integer[] := array[]::integer[];
  v_deleted_ids integer[] := array[]::integer[];
begin
  begin
    if not exists (
      select 1
      from public.admin_operators
      where id = p_operator_id
        and is_active
        and not must_change_password
        and role in ('OWNER', 'OPERATOR')
    ) then
      raise exception '관리자 변경 권한이 없습니다';
    end if;

    if v_action = 'create_teams' then
      with inserted as (
        insert into public.teams (name, short_name, team_color)
        select
          team ->> 'name',
          team ->> 'short_name',
          team ->> 'team_color'
        from jsonb_array_elements(p_payload -> 'teams') as team
        returning id, name, short_name, team_color
      )
      select coalesce(jsonb_agg(to_jsonb(inserted)), '[]'::jsonb)
      into v_after
      from inserted;

      perform public.admin_write_audit(
        p_operator_id,
        'ADMIN_TEAMS_CREATED',
        'team',
        null,
        null,
        v_after,
        true,
        null,
        p_ip_address,
        p_user_agent
      );
      return jsonb_build_object('success', true, 'teams', v_after);
    end if;

    if v_action <> 'save_games' then
      raise exception '지원하지 않는 경기 데이터 작업입니다';
    end if;

    v_target_date := (p_payload ->> 'targetDate')::date;
    perform pg_advisory_xact_lock(
      hashtextextended(
        'admin-game-date:' || v_target_date::text,
        0
      )
    );

    if exists (
      select 1
      from jsonb_array_elements(p_payload -> 'games') as game
      where (game ->> 'game_date')::date <> v_target_date
    ) then
      raise exception '모든 경기 날짜는 저장 대상 날짜와 같아야 합니다';
    end if;

    select coalesce(array_agg((game ->> 'id')::integer), array[]::integer[])
    into v_keep_ids
    from jsonb_array_elements(p_payload -> 'games') as game
    where game ? 'id';

    perform id
    from public.games
    where game_date = v_target_date
    for update;

    select coalesce(jsonb_agg(to_jsonb(g) order by g.id), '[]'::jsonb)
    into v_before
    from public.games g
    where g.game_date = v_target_date;

    if exists (
      select 1
      from public.games g
      join public.markets m on m.game_id = g.id
      where g.game_date = v_target_date
        and not (g.id = any(v_keep_ids))
    ) then
      raise exception '연결된 마켓이 있는 경기는 이 화면에서 삭제할 수 없습니다';
    end if;

    with deleted as (
      delete from public.games g
      where g.game_date = v_target_date
        and not (g.id = any(v_keep_ids))
      returning g.id
    )
    select coalesce(array_agg(id), array[]::integer[])
    into v_deleted_ids
    from deleted;

    for v_game in
      select value
      from jsonb_array_elements(p_payload -> 'games')
    loop
      if v_game ? 'id' then
        v_game_id := (v_game ->> 'id')::integer;
        update public.games
        set
          game_date = (v_game ->> 'game_date')::date,
          game_time = nullif(v_game ->> 'game_time', '')::time,
          home_team_id = (v_game ->> 'home_team_id')::integer,
          away_team_id = (v_game ->> 'away_team_id')::integer,
          home_pitcher = nullif(v_game ->> 'home_pitcher', ''),
          away_pitcher = nullif(v_game ->> 'away_pitcher', ''),
          home_score = nullif(v_game ->> 'home_score', '')::integer,
          away_score = nullif(v_game ->> 'away_score', '')::integer,
          game_status = (v_game ->> 'game_status')::public.game_status,
          updated_at = now()
        where id = v_game_id
          and game_date = v_target_date;

        if not found then
          raise exception '경기를 찾을 수 없습니다: %', v_game_id;
        end if;
      else
        insert into public.games (
          game_date,
          game_time,
          home_team_id,
          away_team_id,
          home_pitcher,
          away_pitcher,
          home_score,
          away_score,
          game_status
        )
        values (
          (v_game ->> 'game_date')::date,
          nullif(v_game ->> 'game_time', '')::time,
          (v_game ->> 'home_team_id')::integer,
          (v_game ->> 'away_team_id')::integer,
          nullif(v_game ->> 'home_pitcher', ''),
          nullif(v_game ->> 'away_pitcher', ''),
          nullif(v_game ->> 'home_score', '')::integer,
          nullif(v_game ->> 'away_score', '')::integer,
          (v_game ->> 'game_status')::public.game_status
        )
        returning id into v_game_id;
        v_inserted_ids := array_append(v_inserted_ids, v_game_id);
      end if;
    end loop;

    select coalesce(jsonb_agg(to_jsonb(g) order by g.id), '[]'::jsonb)
    into v_after
    from public.games g
    where g.game_date = v_target_date;

    perform public.admin_write_audit(
      p_operator_id,
      'ADMIN_GAMES_SAVED',
      'game',
      v_target_date::text,
      v_before,
      jsonb_build_object(
        'games', v_after,
        'insertedIds', v_inserted_ids,
        'deletedIds', v_deleted_ids
      ),
      true,
      null,
      p_ip_address,
      p_user_agent
    );

    return jsonb_build_object(
      'success', true,
      'insertedIds', to_jsonb(v_inserted_ids),
      'deletedIds', to_jsonb(v_deleted_ids)
    );
  exception
    when others then
      get stacked diagnostics v_error = message_text;
      perform public.admin_write_audit(
        p_operator_id,
        case
          when v_action = 'create_teams' then 'ADMIN_TEAMS_CREATED'
          else 'ADMIN_GAMES_SAVED'
        end,
        case
          when v_action = 'create_teams' then 'team'
          else 'game'
        end,
        coalesce(v_target_date::text, null),
        v_before,
        null,
        false,
        v_error,
        p_ip_address,
        p_user_agent
      );
      return jsonb_build_object('success', false, 'error', v_error);
  end;
end;
$$;

create or replace function public.admin_create_operator(
  p_actor_id uuid,
  p_username text,
  p_display_name text,
  p_role public.admin_role,
  p_password_hash text,
  p_ip_address inet,
  p_user_agent text
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_operator public.admin_operators;
  v_after jsonb;
  v_error text;
begin
  begin
    perform 1
    from public.admin_operators
    where id = p_actor_id
      and is_active
      and not must_change_password
      and role = 'OWNER'
    for update;
    if not found then
      raise exception 'OWNER 권한이 필요합니다';
    end if;

    insert into public.admin_operators (
      username,
      display_name,
      role,
      password_hash,
      created_by
    )
    values (
      p_username,
      p_display_name,
      p_role,
      p_password_hash,
      p_actor_id
    )
    returning * into v_operator;

    v_after := jsonb_build_object(
      'id', v_operator.id,
      'username', v_operator.username,
      'display_name', v_operator.display_name,
      'role', v_operator.role,
      'is_active', v_operator.is_active,
      'must_change_password', v_operator.must_change_password,
      'last_login_at', v_operator.last_login_at,
      'created_at', v_operator.created_at,
      'updated_at', v_operator.updated_at
    );

    perform public.admin_write_audit(
      p_actor_id,
      'ADMIN_OPERATOR_CREATED',
      'admin_operator',
      v_operator.id::text,
      null,
      v_after,
      true,
      null,
      p_ip_address,
      p_user_agent
    );
    return jsonb_build_object('success', true, 'operator', v_after);
  exception
    when others then
      get stacked diagnostics v_error = message_text;
      perform public.admin_write_audit(
        p_actor_id,
        'ADMIN_OPERATOR_CREATED',
        'admin_operator',
        null,
        null,
        null,
        false,
        v_error,
        p_ip_address,
        p_user_agent
      );
      return jsonb_build_object('success', false, 'error', v_error);
  end;
end;
$$;

create or replace function public.admin_update_operator(
  p_actor_id uuid,
  p_operator_id uuid,
  p_updates jsonb,
  p_ip_address inet,
  p_user_agent text
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_before public.admin_operators;
  v_after public.admin_operators;
  v_before_json jsonb;
  v_after_json jsonb;
  v_error text;
  v_new_role public.admin_role;
  v_new_is_active boolean;
  v_new_must_change_password boolean;
begin
  begin
    lock table public.admin_operators in share row exclusive mode;

    if not exists (
      select 1
      from public.admin_operators
      where id = p_actor_id
        and is_active
        and not must_change_password
        and role = 'OWNER'
    ) then
      raise exception 'OWNER 권한이 필요합니다';
    end if;

    select *
    into v_before
    from public.admin_operators
    where id = p_operator_id
    for update;
    if not found then
      raise exception '운영자를 찾을 수 없습니다';
    end if;

    v_new_role := coalesce(
      (p_updates ->> 'role')::public.admin_role,
      v_before.role
    );
    v_new_is_active := coalesce(
      (p_updates ->> 'is_active')::boolean,
      v_before.is_active
    );
    v_new_must_change_password := case
      when p_updates ? 'password_hash' then true
      else v_before.must_change_password
    end;

    if v_before.role = 'OWNER'
      and v_before.is_active
      and not v_before.must_change_password
      and (
        v_new_role <> 'OWNER'
        or not v_new_is_active
        or v_new_must_change_password
      )
      and (
        select count(*)
        from public.admin_operators
        where role = 'OWNER'
          and is_active
          and not must_change_password
      ) <= 1
    then
      raise exception '마지막 활성 OWNER는 변경하거나 비활성화할 수 없습니다';
    end if;

    update public.admin_operators
    set
      display_name = coalesce(
        p_updates ->> 'display_name',
        display_name
      ),
      role = v_new_role,
      is_active = v_new_is_active,
      password_hash = coalesce(
        p_updates ->> 'password_hash',
        password_hash
      ),
      must_change_password = case
        when p_updates ? 'password_hash' then true
        else must_change_password
      end,
      password_changed_at = case
        when p_updates ? 'password_hash' then now()
        else password_changed_at
      end
    where id = p_operator_id
    returning * into v_after;

    if not v_after.is_active or p_updates ? 'password_hash' then
      update public.admin_sessions
      set revoked_at = now()
      where operator_id = p_operator_id
        and revoked_at is null;
    end if;

    v_before_json := jsonb_build_object(
      'id', v_before.id,
      'username', v_before.username,
      'display_name', v_before.display_name,
      'role', v_before.role,
      'is_active', v_before.is_active,
      'must_change_password', v_before.must_change_password,
      'last_login_at', v_before.last_login_at,
      'created_at', v_before.created_at,
      'updated_at', v_before.updated_at
    );
    v_after_json := jsonb_build_object(
      'id', v_after.id,
      'username', v_after.username,
      'display_name', v_after.display_name,
      'role', v_after.role,
      'is_active', v_after.is_active,
      'must_change_password', v_after.must_change_password,
      'last_login_at', v_after.last_login_at,
      'created_at', v_after.created_at,
      'updated_at', v_after.updated_at
    );

    perform public.admin_write_audit(
      p_actor_id,
      'ADMIN_OPERATOR_UPDATED',
      'admin_operator',
      p_operator_id::text,
      v_before_json,
      v_after_json,
      true,
      null,
      p_ip_address,
      p_user_agent
    );
    return jsonb_build_object('success', true, 'operator', v_after_json);
  exception
    when others then
      get stacked diagnostics v_error = message_text;
      perform public.admin_write_audit(
        p_actor_id,
        'ADMIN_OPERATOR_UPDATED',
        'admin_operator',
        p_operator_id::text,
        v_before_json,
        null,
        false,
        v_error,
        p_ip_address,
        p_user_agent
      );
      return jsonb_build_object('success', false, 'error', v_error);
  end;
end;
$$;

create or replace function public.admin_change_operator_password(
  p_operator_id uuid,
  p_session_id uuid,
  p_expected_password_hash text,
  p_password_hash text,
  p_ip_address inet,
  p_user_agent text
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_error text;
begin
  begin
    perform 1
    from public.admin_sessions
    where id = p_session_id
      and operator_id = p_operator_id
      and revoked_at is null
      and expires_at > now()
    for update;
    if not found then
      raise exception '현재 관리자 세션을 확인할 수 없습니다';
    end if;

    perform 1
    from public.admin_operators
    where id = p_operator_id
      and is_active
      and password_hash = p_expected_password_hash
    for update;
    if not found then
      raise exception '비밀번호가 변경되었습니다. 다시 로그인해주세요';
    end if;

    update public.admin_operators
    set
      password_hash = p_password_hash,
      must_change_password = false,
      password_changed_at = now()
    where id = p_operator_id
      and is_active;
    if not found then
      raise exception '운영자를 찾을 수 없습니다';
    end if;

    update public.admin_sessions
    set revoked_at = now()
    where operator_id = p_operator_id
      and id <> p_session_id
      and revoked_at is null;

    perform public.admin_write_audit(
      p_operator_id,
      'ADMIN_PASSWORD_CHANGED',
      'admin_operator',
      p_operator_id::text,
      null,
      jsonb_build_object('must_change_password', false),
      true,
      null,
      p_ip_address,
      p_user_agent
    );
    return jsonb_build_object('success', true);
  exception
    when others then
      get stacked diagnostics v_error = message_text;
      perform public.admin_write_audit(
        p_operator_id,
        'ADMIN_PASSWORD_CHANGED',
        'admin_operator',
        p_operator_id::text,
        null,
        null,
        false,
        v_error,
        p_ip_address,
        p_user_agent
      );
      return jsonb_build_object('success', false, 'error', v_error);
  end;
end;
$$;

revoke all on function public.admin_write_audit(
  uuid, text, text, text, jsonb, jsonb, boolean, text, inet, text
) from public, anon, authenticated;
revoke all on function public.admin_execute_rpc(
  uuid, text, jsonb, inet, text
) from public, anon, authenticated;
revoke all on function public.admin_apply_game_data(
  uuid, jsonb, inet, text
) from public, anon, authenticated;
revoke all on function public.admin_create_operator(
  uuid, text, text, public.admin_role, text, inet, text
) from public, anon, authenticated;
revoke all on function public.admin_update_operator(
  uuid, uuid, jsonb, inet, text
) from public, anon, authenticated;
revoke all on function public.admin_change_operator_password(
  uuid, uuid, text, text, inet, text
) from public, anon, authenticated;

grant execute on function public.admin_write_audit(
  uuid, text, text, text, jsonb, jsonb, boolean, text, inet, text
) to service_role;
grant execute on function public.admin_execute_rpc(
  uuid, text, jsonb, inet, text
) to service_role;
grant execute on function public.admin_apply_game_data(
  uuid, jsonb, inet, text
) to service_role;
grant execute on function public.admin_create_operator(
  uuid, text, text, public.admin_role, text, inet, text
) to service_role;
grant execute on function public.admin_update_operator(
  uuid, uuid, jsonb, inet, text
) to service_role;
grant execute on function public.admin_change_operator_password(
  uuid, uuid, text, text, inet, text
) to service_role;

create table if not exists public.admin_login_rate_limits (
  identity text primary key,
  failed_attempts integer not null default 0 check (failed_attempts >= 0),
  window_started_at timestamptz not null default now(),
  blocked_until timestamptz,
  updated_at timestamptz not null default now()
);

alter table public.admin_login_rate_limits enable row level security;
create index if not exists idx_admin_login_rate_limits_updated_at
  on public.admin_login_rate_limits (updated_at);
create index if not exists idx_admin_audit_login_blocked
  on public.admin_audit_logs (action, target_id, created_at desc)
  where action = 'ADMIN_LOGIN_BLOCKED';
revoke all on table public.admin_login_rate_limits
  from public, anon, authenticated;
grant select, insert, update, delete on public.admin_login_rate_limits
  to service_role;

create or replace function public.admin_login_rate_limit_status(
  p_identity text
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_limit public.admin_login_rate_limits;
  v_retry_after integer;
begin
  select *
  into v_limit
  from public.admin_login_rate_limits
  where identity = p_identity;

  if not found or v_limit.blocked_until is null
    or v_limit.blocked_until <= now()
  then
    return jsonb_build_object(
      'allowed', true,
      'retryAfterSeconds', 0
    );
  end if;

  v_retry_after := greatest(
    1,
    ceil(
      extract(epoch from (v_limit.blocked_until - now()))
    )::integer
  );
  return jsonb_build_object(
    'allowed', false,
    'retryAfterSeconds', v_retry_after
  );
end;
$$;

create or replace function public.admin_record_login_attempt(
  p_identity text,
  p_success boolean
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_limit public.admin_login_rate_limits;
  v_failed_attempts integer;
begin
  if p_success then
    delete from public.admin_login_rate_limits
    where identity = p_identity;
    return jsonb_build_object(
      'allowed', true,
      'retryAfterSeconds', 0
    );
  end if;

  select *
  into v_limit
  from public.admin_login_rate_limits
  where identity = p_identity
  for update;

  if not found then
    insert into public.admin_login_rate_limits (
      identity,
      failed_attempts,
      window_started_at,
      blocked_until
    )
    values (
      p_identity,
      1,
      now(),
      null
    );
    return jsonb_build_object(
      'allowed', true,
      'retryAfterSeconds', 0
    );
  end if;

  if v_limit.blocked_until is not null
    and v_limit.blocked_until > now()
  then
    return public.admin_login_rate_limit_status(p_identity);
  end if;

  if v_limit.window_started_at < now() - interval '15 minutes' then
    v_failed_attempts := 1;
    update public.admin_login_rate_limits
    set
      failed_attempts = v_failed_attempts,
      window_started_at = now(),
      blocked_until = null,
      updated_at = now()
    where identity = p_identity;
  else
    v_failed_attempts := v_limit.failed_attempts + 1;
    update public.admin_login_rate_limits
    set
      failed_attempts = v_failed_attempts,
      blocked_until = case
        when v_failed_attempts >= 5 then now() + interval '15 minutes'
        else null
      end,
      updated_at = now()
    where identity = p_identity;
  end if;

  return public.admin_login_rate_limit_status(p_identity);
end;
$$;

revoke all on function public.admin_login_rate_limit_status(text)
  from public, anon, authenticated;
revoke all on function public.admin_record_login_attempt(text, boolean)
  from public, anon, authenticated;
grant execute on function public.admin_login_rate_limit_status(text)
  to service_role;
grant execute on function public.admin_record_login_attempt(text, boolean)
  to service_role;

create or replace function public.admin_complete_login(
  p_operator_id uuid,
  p_token_hash text,
  p_expires_at timestamptz,
  p_rate_identity text,
  p_ip_address inet,
  p_user_agent text
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_session_id uuid;
  v_operator public.admin_operators;
begin
  select *
  into v_operator
  from public.admin_operators
  where id = p_operator_id
    and is_active
  for update;
  if not found then
    raise exception '운영자를 찾을 수 없습니다';
  end if;

  insert into public.admin_sessions (
    operator_id,
    token_hash,
    expires_at
  )
  values (
    p_operator_id,
    p_token_hash,
    p_expires_at
  )
  returning id into v_session_id;

  update public.admin_operators
  set last_login_at = now()
  where id = p_operator_id;

  delete from public.admin_login_rate_limits
  where identity = p_rate_identity;

  perform public.admin_write_audit(
    p_operator_id,
    'ADMIN_LOGIN',
    'admin_operator',
    p_operator_id::text,
    null,
    jsonb_build_object('session_id', v_session_id),
    true,
    null,
    p_ip_address,
    p_user_agent
  );

  return jsonb_build_object(
    'success', true,
    'sessionId', v_session_id
  );
end;
$$;

revoke all on function public.admin_complete_login(
  uuid, text, timestamptz, text, inet, text
) from public, anon, authenticated;
grant execute on function public.admin_complete_login(
  uuid, text, timestamptz, text, inet, text
) to service_role;

drop function public.admin_complete_login(
  uuid, text, timestamptz, text, inet, text
);
drop function public.admin_login_rate_limit_status(text);
drop function public.admin_record_login_attempt(text, boolean);

create or replace function public.admin_reserve_login_limit(
  p_key text
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_limit public.admin_login_rate_limits;
  v_failed_attempts integer;
  v_retry_after integer;
begin
  select *
  into v_limit
  from public.admin_login_rate_limits
  where identity = p_key;

  if found
    and v_limit.blocked_until is not null
    and v_limit.blocked_until > now()
  then
    v_retry_after := greatest(
      1,
      ceil(
        extract(epoch from (v_limit.blocked_until - now()))
      )::integer
    );
    return jsonb_build_object(
      'allowed', false,
      'retryAfterSeconds', v_retry_after
    );
  end if;

  if not found then
    insert into public.admin_login_rate_limits (
      identity,
      failed_attempts,
      window_started_at,
      blocked_until
    )
    values (p_key, 0, now(), null)
    returning * into v_limit;
  elsif v_limit.window_started_at < now() - interval '15 minutes' then
    update public.admin_login_rate_limits
    set
      failed_attempts = 0,
      window_started_at = now(),
      blocked_until = null,
      updated_at = now()
    where identity = p_key
    returning * into v_limit;
  end if;

  v_failed_attempts := v_limit.failed_attempts + 1;
  update public.admin_login_rate_limits
  set
    failed_attempts = v_failed_attempts,
    blocked_until = case
      when v_failed_attempts >= 5
        then now() + interval '15 minutes'
      else null
    end,
    updated_at = now()
  where identity = p_key;

  return jsonb_build_object(
    'allowed', true,
    'attemptNumber', v_failed_attempts,
    'retryAfterSeconds', 0
  );
end;
$$;

create or replace function public.admin_begin_login_attempt(
  p_identity text,
  p_username text,
  p_ip_address inet,
  p_user_agent text
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_account_key text;
  v_ip_key text;
  v_first_key text;
  v_second_key text;
  v_known_account boolean;
  v_limit_count integer;
  v_account_result jsonb;
  v_ip_result jsonb;
  v_blocked_key text;
  v_retry_after integer;
  v_attempt_id bigint;
begin
  select exists (
    select 1
    from public.admin_operators
    where lower(username) = lower(btrim(p_username))
  )
  into v_known_account;

  if v_known_account then
    v_account_key := 'account:' || lower(btrim(p_username));
  end if;
  v_ip_key := case
    when p_ip_address is null then 'ip:unknown'
    when family(p_ip_address) = 4 then
      'ip:' || host(network(set_masklen(p_ip_address, 24)))
    else
      'ip:' || host(network(set_masklen(p_ip_address, 64)))
  end;

  delete from public.admin_login_rate_limits
  where ctid in (
    select ctid
    from public.admin_login_rate_limits
    where updated_at < now() - interval '24 hours'
    order by updated_at
    limit 1000
  );

  if not v_known_account
    and not exists (
      select 1
      from public.admin_login_rate_limits
      where identity = v_ip_key
    )
  then
    perform pg_advisory_xact_lock(
      hashtextextended('admin-login-limit-cap', 0)
    );
    select count(*)
    into v_limit_count
    from public.admin_login_rate_limits;
    if v_limit_count >= 10000 then
      v_ip_key := 'ip:overflow';
    end if;
  end if;

  v_first_key := case
    when v_account_key is null then v_ip_key
    else least(v_account_key, v_ip_key)
  end;
  v_second_key := case
    when v_account_key is null then v_ip_key
    else greatest(v_account_key, v_ip_key)
  end;
  perform pg_advisory_xact_lock(
    hashtextextended(v_first_key, 0)
  );
  if v_second_key <> v_first_key then
    perform pg_advisory_xact_lock(
      hashtextextended(v_second_key, 0)
    );
  end if;

  if v_known_account then
    v_account_result :=
      public.admin_reserve_login_limit(v_account_key);
    if not (v_account_result ->> 'allowed')::boolean then
      v_blocked_key := v_account_key;
      v_retry_after :=
        (v_account_result ->> 'retryAfterSeconds')::integer;
    end if;
  end if;

  if v_blocked_key is null then
    v_ip_result := public.admin_reserve_login_limit(v_ip_key);
    if not (v_ip_result ->> 'allowed')::boolean then
      v_blocked_key := v_ip_key;
      v_retry_after :=
        (v_ip_result ->> 'retryAfterSeconds')::integer;
    end if;
  end if;

  if v_blocked_key is not null then
    if not exists (
      select 1
      from public.admin_audit_logs
      where action = 'ADMIN_LOGIN_BLOCKED'
        and target_id = v_blocked_key
        and created_at > now() - interval '1 minute'
    ) then
      insert into public.admin_audit_logs (
        action,
        target_type,
        target_id,
        after_state,
        success,
        error_message,
        ip_address,
        user_agent
      )
      values (
        'ADMIN_LOGIN_BLOCKED',
        'admin_login_limit',
        v_blocked_key,
        jsonb_build_object(
          'identity', p_identity,
          'accountKey', v_account_key,
          'ipKey', v_ip_key
        ),
        false,
        '로그인 시도 횟수를 초과했습니다.',
        p_ip_address,
        p_user_agent
      );
    end if;
    return jsonb_build_object(
      'allowed', false,
      'retryAfterSeconds', v_retry_after
    );
  end if;

  insert into public.admin_audit_logs (
    action,
    target_type,
    target_id,
    after_state,
    success,
    error_message,
    ip_address,
    user_agent
  )
  values (
    'ADMIN_LOGIN_ATTEMPT',
    'admin_operator',
    p_username,
    jsonb_build_object(
      'identity', p_identity,
      'accountKey', v_account_key,
      'ipKey', v_ip_key,
      'accountAttempt',
      v_account_result -> 'attemptNumber',
      'ipAttempt',
      v_ip_result -> 'attemptNumber'
    ),
    false,
    'AUTHENTICATION_PENDING',
    p_ip_address,
    p_user_agent
  )
  returning id into v_attempt_id;

  return jsonb_build_object(
    'allowed', true,
    'attemptId', v_attempt_id,
    'retryAfterSeconds', 0
  );
end;
$$;

create or replace function public.admin_fail_login_attempt(
  p_attempt_id bigint,
  p_error_message text
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
begin
  update public.admin_audit_logs
  set error_message = p_error_message
  where id = p_attempt_id
    and action = 'ADMIN_LOGIN_ATTEMPT'
    and not success;
  if not found then
    raise exception '로그인 시도 기록을 찾을 수 없습니다';
  end if;
  return jsonb_build_object('success', true);
end;
$$;

create or replace function public.admin_complete_login(
  p_operator_id uuid,
  p_expected_password_hash text,
  p_token_hash text,
  p_expires_at timestamptz,
  p_rate_identity text,
  p_attempt_id bigint,
  p_ip_address inet,
  p_user_agent text
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_session_id uuid;
  v_username text;
  v_account_key text;
  v_ip_key text;
  v_first_key text;
  v_second_key text;
begin
  perform 1
  from public.admin_audit_logs
  where id = p_attempt_id
    and action = 'ADMIN_LOGIN_ATTEMPT'
    and not success
  for update;
  if not found then
    raise exception '로그인 시도 기록을 찾을 수 없습니다';
  end if;

  select username
  into v_username
  from public.admin_operators
  where id = p_operator_id
    and is_active
    and password_hash = p_expected_password_hash
  for update;
  if not found then
    raise exception '운영자를 찾을 수 없습니다';
  end if;

  v_account_key := 'account:' || lower(btrim(v_username));
  v_ip_key := case
    when p_ip_address is null then 'ip:unknown'
    when family(p_ip_address) = 4 then
      'ip:' || host(network(set_masklen(p_ip_address, 24)))
    else
      'ip:' || host(network(set_masklen(p_ip_address, 64)))
  end;
  v_first_key := least(v_account_key, v_ip_key);
  v_second_key := greatest(v_account_key, v_ip_key);
  perform pg_advisory_xact_lock(
    hashtextextended(v_first_key, 0)
  );
  if v_second_key <> v_first_key then
    perform pg_advisory_xact_lock(
      hashtextextended(v_second_key, 0)
    );
  end if;

  insert into public.admin_sessions (
    operator_id,
    token_hash,
    expires_at
  )
  values (
    p_operator_id,
    p_token_hash,
    p_expires_at
  )
  returning id into v_session_id;

  update public.admin_operators
  set last_login_at = now()
  where id = p_operator_id;

  delete from public.admin_login_rate_limits
  where identity in (v_account_key, v_ip_key);

  update public.admin_audit_logs
  set
    operator_id = p_operator_id,
    action = 'ADMIN_LOGIN',
    target_id = p_operator_id::text,
    after_state = after_state || jsonb_build_object(
      'sessionId', v_session_id,
      'rateIdentity', p_rate_identity
    ),
    success = true,
    error_message = null,
    ip_address = p_ip_address,
    user_agent = p_user_agent
  where id = p_attempt_id;

  return jsonb_build_object(
    'success', true,
    'sessionId', v_session_id
  );
end;
$$;

revoke all on function public.admin_reserve_login_limit(text)
  from public, anon, authenticated;
revoke all on function public.admin_begin_login_attempt(
  text, text, inet, text
) from public, anon, authenticated;
revoke all on function public.admin_fail_login_attempt(bigint, text)
  from public, anon, authenticated;
revoke all on function public.admin_complete_login(
  uuid, text, text, timestamptz, text, bigint, inet, text
) from public, anon, authenticated;
grant execute on function public.admin_begin_login_attempt(
  text, text, inet, text
) to service_role;
grant execute on function public.admin_fail_login_attempt(bigint, text)
  to service_role;
grant execute on function public.admin_complete_login(
  uuid, text, text, timestamptz, text, bigint, inet, text
) to service_role;

create or replace function public.lock_game_date_mutation()
returns trigger
language plpgsql
set search_path = public
as $$
declare
  v_first_date date;
  v_second_date date;
begin
  if tg_op = 'INSERT' then
    perform pg_advisory_xact_lock(
      hashtextextended(
        'admin-game-date:' || new.game_date::text,
        0
      )
    );
    return new;
  end if;

  if tg_op = 'DELETE' then
    perform pg_advisory_xact_lock(
      hashtextextended(
        'admin-game-date:' || old.game_date::text,
        0
      )
    );
    return old;
  end if;

  v_first_date := least(old.game_date, new.game_date);
  v_second_date := greatest(old.game_date, new.game_date);
  perform pg_advisory_xact_lock(
    hashtextextended(
      'admin-game-date:' || v_first_date::text,
      0
    )
  );
  if v_second_date <> v_first_date then
    perform pg_advisory_xact_lock(
      hashtextextended(
        'admin-game-date:' || v_second_date::text,
        0
      )
    );
  end if;
  return new;
end;
$$;

drop trigger if exists trg_lock_game_date_mutations
  on public.games;
create trigger trg_lock_game_date_mutations
before insert or update or delete on public.games
for each row
execute function public.lock_game_date_mutation();
