-- Issue #41: KST weekly grant policy, scheduler controls, and idempotent rounds.

create table if not exists public.weekly_grant_policies (
  id integer generated by default as identity primary key,
  season_id integer not null unique references public.seasons(id),
  amount numeric not null check (amount > 0),
  weekday smallint not null check (weekday between 1 and 7),
  grant_time time not null,
  automatic_enabled boolean not null default true,
  is_paused boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.weekly_grant_runs (
  id integer generated by default as identity primary key,
  season_id integer not null references public.seasons(id),
  round_key text not null,
  source text not null check (source in ('AUTO', 'MANUAL')),
  status text not null check (status in ('RUNNING', 'SUCCESS', 'FAILURE', 'SKIPPED')),
  scheduled_for timestamptz,
  recipient_count integer not null default 0,
  total_payout numeric not null default 0,
  failure_count integer not null default 0,
  error_message text,
  initiated_by uuid references public.admin_operators(id) on delete set null,
  started_at timestamptz not null default now(),
  completed_at timestamptz,
  unique (season_id, round_key)
);

create table if not exists public.weekly_grant_run_recipients (
  run_id integer not null references public.weekly_grant_runs(id) on delete cascade,
  user_id uuid not null references public.users(id),
  amount numeric not null check (amount > 0),
  balance_after numeric not null,
  primary key (run_id, user_id)
);

alter table public.weekly_grant_policies enable row level security;
alter table public.weekly_grant_runs enable row level security;
alter table public.weekly_grant_run_recipients enable row level security;

insert into public.weekly_grant_policies (
  season_id, amount, weekday, grant_time, automatic_enabled, is_paused
)
select id, 300, 1, time '00:00', true, false
from public.seasons
where status = 'ACTIVE'
on conflict (season_id) do nothing;

create or replace function public.weekly_grant_cron_expression(
  p_weekday integer,
  p_grant_time time
)
returns text
language plpgsql
immutable
as $$
declare
  v_kst_dow integer;
  v_utc_dow integer;
  v_hour integer;
  v_minute integer;
begin
  if p_weekday not between 1 and 7 then
    raise exception '요일은 1(월)부터 7(일) 사이여야 합니다';
  end if;
  v_hour := extract(hour from p_grant_time)::integer;
  v_minute := extract(minute from p_grant_time)::integer;
  v_kst_dow := p_weekday % 7;
  v_utc_dow := (v_kst_dow - case when v_hour < 9 then 1 else 0 end + 7) % 7;
  return format(
    '%s %s * * %s',
    v_minute,
    (v_hour + 15) % 24,
    v_utc_dow
  );
end;
$$;

create or replace function public.weekly_grant_next_run(
  p_weekday integer,
  p_grant_time time
)
returns timestamptz
language sql
stable
as $$
  select min(
    (candidate.day + p_grant_time) at time zone 'Asia/Seoul'
  )
  from generate_series(
    (now() at time zone 'Asia/Seoul')::date,
    (now() at time zone 'Asia/Seoul')::date + 14,
    interval '1 day'
  ) as candidate(day)
  where extract(isodow from candidate.day)::integer = p_weekday
    and candidate.day + p_grant_time >
      now() at time zone 'Asia/Seoul';
$$;

create or replace function public.sync_weekly_grant_cron()
returns void
language plpgsql
security definer
set search_path = public, cron
as $$
declare
  v_policy public.weekly_grant_policies;
  v_schedule text;
  v_job_id bigint;
begin
  select p.*
  into v_policy
  from public.weekly_grant_policies p
  join public.seasons s on s.id = p.season_id
  where s.status = 'ACTIVE'
  limit 1;

  if not found then
    return;
  end if;

  v_schedule := public.weekly_grant_cron_expression(
    v_policy.weekday,
    v_policy.grant_time
  );
  select jobid into v_job_id
  from cron.job
  where jobname = 'weekly_coin_distribution';

  if v_job_id is null then
    perform cron.schedule(
      'weekly_coin_distribution',
      v_schedule,
      'SELECT public.run_scheduled_weekly_grant();'
    );
    select jobid into v_job_id
    from cron.job
    where jobname = 'weekly_coin_distribution';
  end if;

  perform cron.alter_job(
    v_job_id,
    schedule := v_schedule,
    command := 'SELECT public.run_scheduled_weekly_grant();',
    active := v_policy.automatic_enabled and not v_policy.is_paused
  );
end;
$$;

create or replace function public.get_weekly_grant_status()
returns jsonb
language plpgsql
security definer
set search_path = public, cron
as $$
declare
  v_policy public.weekly_grant_policies;
  v_season public.seasons;
  v_recipient_count integer;
  v_job cron.job;
  v_runs jsonb;
begin
  select * into v_season
  from public.seasons where status = 'ACTIVE' limit 1;
  if not found then
    raise exception '활성 시즌이 없습니다';
  end if;

  select * into v_policy
  from public.weekly_grant_policies
  where season_id = v_season.id;
  if not found then
    raise exception '주간 지급 정책을 찾을 수 없습니다';
  end if;

  select count(*) into v_recipient_count from public.users;
  select * into v_job
  from cron.job where jobname = 'weekly_coin_distribution';
  select coalesce(jsonb_agg(to_jsonb(r) order by r.started_at desc), '[]'::jsonb)
  into v_runs
  from (
    select id, round_key, source, status, scheduled_for,
      recipient_count, total_payout, failure_count,
      error_message, started_at, completed_at
    from public.weekly_grant_runs
    where season_id = v_season.id
    order by started_at desc
    limit 10
  ) r;

  return jsonb_build_object(
    'season_id', v_season.id,
    'season_name', v_season.name,
    'amount', v_policy.amount,
    'weekday', v_policy.weekday,
    'grant_time', to_char(v_policy.grant_time, 'HH24:MI'),
    'automatic_enabled', v_policy.automatic_enabled,
    'is_paused', v_policy.is_paused,
    'cron_expression', public.weekly_grant_cron_expression(
      v_policy.weekday, v_policy.grant_time
    ),
    'cron_active', coalesce(v_job.active, false),
    'next_run', case
      when v_policy.automatic_enabled and not v_policy.is_paused
      then public.weekly_grant_next_run(v_policy.weekday, v_policy.grant_time)
      else null
    end,
    'expected_recipient_count', v_recipient_count,
    'estimated_total_payout', v_recipient_count * v_policy.amount,
    'recent_runs', v_runs
  );
end;
$$;

create or replace function public.admin_update_weekly_grant_policy(
  p_operator_id uuid,
  p_amount numeric,
  p_weekday integer,
  p_grant_time time,
  p_automatic_enabled boolean
)
returns jsonb
language plpgsql
security definer
set search_path = public, cron
as $$
declare
  v_season public.seasons;
  v_before public.weekly_grant_policies;
  v_after public.weekly_grant_policies;
begin
  if p_amount is null or p_amount <= 0 then
    raise exception '지급액은 0보다 커야 합니다';
  end if;
  perform public.weekly_grant_cron_expression(p_weekday, p_grant_time);
  select * into v_season from public.seasons where status = 'ACTIVE' limit 1;
  if not found then raise exception '활성 시즌이 없습니다'; end if;

  select * into v_before
  from public.weekly_grant_policies
  where season_id = v_season.id
  for update;

  insert into public.weekly_grant_policies (
    season_id, amount, weekday, grant_time, automatic_enabled, is_paused
  )
  values (
    v_season.id, p_amount, p_weekday, p_grant_time,
    p_automatic_enabled, false
  )
  on conflict (season_id) do update
  set amount = excluded.amount,
      weekday = excluded.weekday,
      grant_time = excluded.grant_time,
      automatic_enabled = excluded.automatic_enabled,
      updated_at = now()
  returning * into v_after;

  perform public.sync_weekly_grant_cron();
  insert into public.admin_audit_logs (
    operator_id, action, target_type, target_id,
    before_state, after_state, success
  ) values (
    p_operator_id, 'WEEKLY_GRANT_POLICY_UPDATE', 'season',
    v_season.id::text, to_jsonb(v_before), to_jsonb(v_after), true
  );
  return public.get_weekly_grant_status();
end;
$$;

create or replace function public.admin_set_weekly_grant_pause(
  p_operator_id uuid,
  p_paused boolean
)
returns jsonb
language plpgsql
security definer
set search_path = public, cron
as $$
declare
  v_policy public.weekly_grant_policies;
begin
  update public.weekly_grant_policies p
  set is_paused = p_paused, updated_at = now()
  from public.seasons s
  where s.id = p.season_id and s.status = 'ACTIVE'
  returning p.* into v_policy;
  if not found then raise exception '주간 지급 정책을 찾을 수 없습니다'; end if;
  perform public.sync_weekly_grant_cron();
  insert into public.admin_audit_logs (
    operator_id, action, target_type, target_id, after_state, success
  ) values (
    p_operator_id,
    case when p_paused then 'WEEKLY_GRANT_PAUSE' else 'WEEKLY_GRANT_RESUME' end,
    'season', v_policy.season_id::text, to_jsonb(v_policy), true
  );
  return public.get_weekly_grant_status();
end;
$$;

create or replace function public.run_weekly_grant_round(
  p_operator_id uuid,
  p_round_key text,
  p_source text,
  p_scheduled_for timestamptz default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_policy public.weekly_grant_policies;
  v_season public.seasons;
  v_run public.weekly_grant_runs;
  v_recipient_count integer;
  v_total numeric;
begin
  if btrim(coalesce(p_round_key, '')) = '' then
    raise exception '지급 라운드를 입력해주세요';
  end if;
  if upper(p_source) not in ('AUTO', 'MANUAL') then
    raise exception '지급 실행 구분이 올바르지 않습니다';
  end if;
  select * into v_season from public.seasons where status = 'ACTIVE' limit 1;
  if not found then raise exception '활성 시즌이 없습니다'; end if;
  select * into v_policy from public.weekly_grant_policies
  where season_id = v_season.id;

  insert into public.weekly_grant_runs (
    season_id, round_key, source, status, scheduled_for, initiated_by
  ) values (
    v_season.id, btrim(p_round_key), upper(p_source), 'RUNNING',
    p_scheduled_for, p_operator_id
  )
  on conflict (season_id, round_key) do nothing;

  select * into v_run from public.weekly_grant_runs
  where season_id = v_season.id and round_key = btrim(p_round_key)
  for update;

  if v_run.status = 'SUCCESS' then
    return jsonb_build_object(
      'status', 'SKIPPED', 'run_id', v_run.id,
      'round_key', v_run.round_key, 'message', '이미 지급된 라운드입니다'
    );
  end if;
  if upper(p_source) = 'AUTO'
    and (not v_policy.automatic_enabled or v_policy.is_paused) then
    update public.weekly_grant_runs
    set status = 'SKIPPED', completed_at = now(),
        error_message = '자동 지급이 일시정지되었습니다'
    where id = v_run.id;
    return jsonb_build_object(
      'status', 'SKIPPED', 'run_id', v_run.id,
      'round_key', v_run.round_key,
      'message', '자동 지급이 일시정지되었습니다'
    );
  end if;

  update public.weekly_grant_runs
  set source = upper(p_source), status = 'RUNNING',
      initiated_by = p_operator_id, started_at = now(),
      completed_at = null, error_message = null
  where id = v_run.id;

  begin
    insert into public.wallets (user_id, season_id, balance)
    select id, v_season.id, 0 from public.users
    on conflict (user_id, season_id) do nothing;

    with updated as (
      update public.wallets w
      set balance = w.balance + v_policy.amount, updated_at = now()
      where w.season_id = v_season.id
      returning w.user_id, w.balance
    ), recipient_rows as (
      insert into public.weekly_grant_run_recipients (
        run_id, user_id, amount, balance_after
      )
      select v_run.id, user_id, v_policy.amount, balance from updated
      returning user_id, balance_after
    ), transaction_rows as (
      insert into public.transactions (
        user_id, type, amount, balance_after, reference_id,
        description, season_id
      )
      select user_id, 'WEEKLY_GRANT', v_policy.amount, balance_after,
        v_run.id, '주간 코인 지급 ' || btrim(p_round_key), v_season.id
      from recipient_rows
      returning user_id
    )
    select count(*), count(*) * v_policy.amount
    into v_recipient_count, v_total
    from transaction_rows;

    update public.weekly_grant_runs
    set status = 'SUCCESS', recipient_count = v_recipient_count,
        total_payout = v_total, failure_count = 0, completed_at = now()
    where id = v_run.id;
  exception when others then
    update public.weekly_grant_runs
    set status = 'FAILURE', failure_count = 1,
        error_message = sqlerrm, completed_at = now()
    where id = v_run.id;
    insert into public.admin_audit_logs (
      operator_id, action, target_type, target_id, after_state, success,
      error_message
    ) values (
      p_operator_id, 'WEEKLY_GRANT_' || upper(p_source) || '_RUN',
      'weekly_grant_run', v_run.id::text,
      jsonb_build_object('round_key', p_round_key, 'status', 'FAILURE'),
      false, sqlerrm
    );
    return jsonb_build_object(
      'status', 'FAILURE', 'run_id', v_run.id,
      'round_key', p_round_key, 'error', sqlerrm
    );
  end;

  insert into public.admin_audit_logs (
    operator_id, action, target_type, target_id, after_state, success
  ) values (
    p_operator_id, 'WEEKLY_GRANT_' || upper(p_source) || '_RUN',
    'weekly_grant_run', v_run.id::text,
    jsonb_build_object(
      'round_key', p_round_key, 'status', 'SUCCESS',
      'recipient_count', v_recipient_count, 'total_payout', v_total
    ), true
  );
  return jsonb_build_object(
    'status', 'SUCCESS', 'run_id', v_run.id,
    'round_key', p_round_key, 'recipient_count', v_recipient_count,
    'total_payout', v_total
  );
end;
$$;

create or replace function public.run_scheduled_weekly_grant()
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
begin
  return public.run_weekly_grant_round(
    null,
    to_char(now() at time zone 'Asia/Seoul', 'IYYY-IW'),
    'AUTO',
    now()
  );
end;
$$;

create or replace function public.distribute_weekly_coins(
  p_amount numeric default 300
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_policy public.weekly_grant_policies;
begin
  select p.* into v_policy
  from public.weekly_grant_policies p
  join public.seasons s on s.id = p.season_id
  where s.status = 'ACTIVE'
  limit 1;
  if not found then
    return jsonb_build_object('success', false, 'error', '주간 지급 정책을 찾을 수 없습니다');
  end if;
  if p_amount <> v_policy.amount then
    return jsonb_build_object('success', false, 'error', '저장된 주간 지급액과 일치하지 않습니다');
  end if;
  return public.run_weekly_grant_round(
    null,
    to_char(now() at time zone 'Asia/Seoul', 'IYYY-IW'),
    'MANUAL',
    now()
  );
end;
$$;

select public.sync_weekly_grant_cron();

revoke all on table public.weekly_grant_policies from anon, authenticated;
revoke all on table public.weekly_grant_runs from anon, authenticated;
revoke all on table public.weekly_grant_run_recipients from anon, authenticated;
grant select, insert, update on public.weekly_grant_policies to service_role;
grant select, insert, update on public.weekly_grant_runs to service_role;
grant select, insert on public.weekly_grant_run_recipients to service_role;
grant usage, select on all sequences in schema public to service_role;

revoke all on function public.get_weekly_grant_status() from public, anon, authenticated;
revoke all on function public.admin_update_weekly_grant_policy(uuid,numeric,integer,time,boolean) from public, anon, authenticated;
revoke all on function public.admin_set_weekly_grant_pause(uuid,boolean) from public, anon, authenticated;
revoke all on function public.run_weekly_grant_round(uuid,text,text,timestamptz) from public, anon, authenticated;
grant execute on function public.get_weekly_grant_status() to service_role;
grant execute on function public.admin_update_weekly_grant_policy(uuid,numeric,integer,time,boolean) to service_role;
grant execute on function public.admin_set_weekly_grant_pause(uuid,boolean) to service_role;
grant execute on function public.run_weekly_grant_round(uuid,text,text,timestamptz) to service_role;
