-- Issue #38: governed team master data, source aliases, pending mappings, and safe merges.

alter table public.teams
  add column if not exists is_active boolean not null default true,
  add column if not exists merged_into_team_id integer references public.teams(id),
  add column if not exists updated_at timestamptz not null default now();

create unique index if not exists teams_active_name_unique_idx
  on public.teams (lower(btrim(name)))
  where is_active;

create unique index if not exists teams_active_short_name_unique_idx
  on public.teams (lower(btrim(short_name)))
  where is_active;

select setval(
  pg_get_serial_sequence('public.teams', 'id'),
  coalesce((select max(id) from public.teams), 1),
  exists (select 1 from public.teams)
);

create table if not exists public.team_aliases (
  id bigint generated by default as identity primary key,
  source text not null check (btrim(source) <> ''),
  alias text not null check (btrim(alias) <> ''),
  normalized_alias text generated always as (lower(btrim(alias))) stored,
  team_id integer not null references public.teams(id),
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists team_aliases_active_source_alias_unique_idx
  on public.team_aliases (upper(btrim(source)), normalized_alias)
  where is_active;

create index if not exists team_aliases_team_idx
  on public.team_aliases (team_id, source);

create table if not exists public.team_mapping_requests (
  id bigint generated by default as identity primary key,
  source text not null check (btrim(source) <> ''),
  external_name text not null check (btrim(external_name) <> ''),
  normalized_external_name text
    generated always as (lower(btrim(external_name))) stored,
  status text not null default 'PENDING'
    check (status in ('PENDING', 'MAPPED', 'DISMISSED')),
  mapped_team_id integer references public.teams(id),
  occurrence_count integer not null default 1 check (occurrence_count > 0),
  first_seen_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  resolved_at timestamptz,
  resolved_by uuid references public.admin_operators(id) on delete set null
);

create unique index if not exists team_mapping_requests_pending_unique_idx
  on public.team_mapping_requests (
    upper(btrim(source)),
    normalized_external_name
  )
  where status = 'PENDING';

create index if not exists team_mapping_requests_status_seen_idx
  on public.team_mapping_requests (status, last_seen_at desc);

alter table public.team_aliases enable row level security;
alter table public.team_mapping_requests enable row level security;

create or replace function public.admin_upsert_team(
  p_operator_id uuid,
  p_team_id integer,
  p_name text,
  p_short_name text,
  p_team_color text
)
returns public.teams
language plpgsql
security definer
set search_path = public
as $$
declare
  v_before public.teams;
  v_team public.teams;
begin
  if btrim(coalesce(p_name, '')) = '' then
    raise exception '팀 이름을 입력해주세요';
  end if;
  if btrim(coalesce(p_short_name, '')) = '' then
    raise exception '팀 약칭을 입력해주세요';
  end if;
  if p_team_color !~ '^#[0-9A-F]{6}$' then
    raise exception '팀 색상은 #RRGGBB 형식이어야 합니다';
  end if;

  if p_team_id is null then
    insert into public.teams (name, short_name, team_color)
    values (btrim(p_name), btrim(p_short_name), p_team_color)
    returning * into v_team;

    insert into public.admin_audit_logs (
      operator_id, action, target_type, target_id, after_state, success
    )
    values (
      p_operator_id,
      'TEAM_CREATE',
      'team',
      v_team.id::text,
      to_jsonb(v_team),
      true
    );
  else
    select *
    into v_before
    from public.teams
    where id = p_team_id
    for update;

    if not found then
      raise exception '팀을 찾을 수 없습니다';
    end if;
    if not v_before.is_active then
      raise exception '비활성 팀은 수정할 수 없습니다';
    end if;

    update public.teams
    set name = btrim(p_name),
        short_name = btrim(p_short_name),
        team_color = p_team_color,
        updated_at = now()
    where id = p_team_id
    returning * into v_team;

    insert into public.admin_audit_logs (
      operator_id, action, target_type, target_id,
      before_state, after_state, success
    )
    values (
      p_operator_id,
      'TEAM_UPDATE',
      'team',
      v_team.id::text,
      to_jsonb(v_before),
      to_jsonb(v_team),
      true
    );
  end if;

  return v_team;
end;
$$;

create or replace function public.admin_upsert_team_alias(
  p_operator_id uuid,
  p_alias_id bigint,
  p_source text,
  p_alias text,
  p_team_id integer
)
returns public.team_aliases
language plpgsql
security definer
set search_path = public
as $$
declare
  v_before public.team_aliases;
  v_alias public.team_aliases;
begin
  if btrim(coalesce(p_source, '')) = '' then
    raise exception '소스를 입력해주세요';
  end if;
  if btrim(coalesce(p_alias, '')) = '' then
    raise exception '별칭을 입력해주세요';
  end if;
  if not exists (
    select 1 from public.teams where id = p_team_id and is_active
  ) then
    raise exception '활성 팀을 찾을 수 없습니다';
  end if;

  if p_alias_id is null then
    insert into public.team_aliases (source, alias, team_id)
    values (upper(btrim(p_source)), btrim(p_alias), p_team_id)
    returning * into v_alias;

    insert into public.admin_audit_logs (
      operator_id, action, target_type, target_id, after_state, success
    )
    values (
      p_operator_id,
      'TEAM_ALIAS_CREATE',
      'team_alias',
      v_alias.id::text,
      to_jsonb(v_alias),
      true
    );
  else
    select *
    into v_before
    from public.team_aliases
    where id = p_alias_id
    for update;

    if not found then
      raise exception '팀 별칭을 찾을 수 없습니다';
    end if;

    update public.team_aliases
    set source = upper(btrim(p_source)),
        alias = btrim(p_alias),
        team_id = p_team_id,
        is_active = true,
        updated_at = now()
    where id = p_alias_id
    returning * into v_alias;

    insert into public.admin_audit_logs (
      operator_id, action, target_type, target_id,
      before_state, after_state, success
    )
    values (
      p_operator_id,
      'TEAM_ALIAS_UPDATE',
      'team_alias',
      v_alias.id::text,
      to_jsonb(v_before),
      to_jsonb(v_alias),
      true
    );
  end if;

  return v_alias;
end;
$$;

create or replace function public.resolve_team_mappings(
  p_source text,
  p_external_names text[]
)
returns table (
  external_name text,
  mapping_status text,
  team_id integer,
  team_name text,
  request_id bigint
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_name text;
  v_team public.teams;
  v_request_id bigint;
begin
  if btrim(coalesce(p_source, '')) = '' then
    raise exception '소스를 입력해주세요';
  end if;

  for v_name in
    select distinct btrim(value)
    from unnest(coalesce(p_external_names, array[]::text[])) as names(value)
    where btrim(value) <> ''
  loop
    select t.*
    into v_team
    from public.teams t
    where t.is_active
      and (
        lower(btrim(t.name)) = lower(v_name)
        or lower(btrim(t.short_name)) = lower(v_name)
      )
    limit 1;

    if not found then
      select t.*
      into v_team
      from public.team_aliases a
      join public.teams t on t.id = a.team_id
      where a.is_active
        and t.is_active
        and upper(btrim(a.source)) = upper(btrim(p_source))
        and a.normalized_alias = lower(v_name)
      limit 1;
    end if;

    if found then
      external_name := v_name;
      mapping_status := 'MAPPED';
      team_id := v_team.id;
      team_name := v_team.name;
      request_id := null;
      return next;
    else
      insert into public.team_mapping_requests (
        source, external_name, status
      )
      values (
        upper(btrim(p_source)), v_name, 'PENDING'
      )
      on conflict (
        (upper(btrim(source))),
        normalized_external_name
      ) where status = 'PENDING'
      do update
      set occurrence_count =
            public.team_mapping_requests.occurrence_count + 1,
          last_seen_at = now(),
          external_name = excluded.external_name
      returning id into v_request_id;

      external_name := v_name;
      mapping_status := 'PENDING';
      team_id := null;
      team_name := null;
      request_id := v_request_id;
      return next;
    end if;
  end loop;
end;
$$;

create or replace function public.admin_approve_team_mapping(
  p_operator_id uuid,
  p_request_id bigint,
  p_team_id integer,
  p_name text,
  p_short_name text,
  p_team_color text
)
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  v_request public.team_mapping_requests;
  v_team public.teams;
  v_team_id integer;
  v_alias public.team_aliases;
begin
  select *
  into v_request
  from public.team_mapping_requests
  where id = p_request_id
    and status = 'PENDING'
  for update;

  if not found then
    raise exception '대기 중인 매핑 요청을 찾을 수 없습니다';
  end if;

  if p_team_id is null then
    v_team := public.admin_upsert_team(
      p_operator_id,
      null,
      p_name,
      p_short_name,
      p_team_color
    );
    v_team_id := v_team.id;
  else
    select *
    into v_team
    from public.teams
    where id = p_team_id and is_active;

    if not found then
      raise exception '매핑할 활성 팀을 찾을 수 없습니다';
    end if;
    v_team_id := v_team.id;
  end if;

  v_alias := public.admin_upsert_team_alias(
    p_operator_id,
    null,
    v_request.source,
    v_request.external_name,
    v_team_id
  );

  update public.team_mapping_requests
  set status = 'MAPPED',
      mapped_team_id = v_team_id,
      resolved_at = now(),
      resolved_by = p_operator_id
  where id = p_request_id;

  insert into public.admin_audit_logs (
    operator_id, action, target_type, target_id,
    before_state, after_state, success
  )
  values (
    p_operator_id,
    'TEAM_MAPPING_APPROVE',
    'team_mapping_request',
    p_request_id::text,
    to_jsonb(v_request),
    jsonb_build_object(
      'status', 'MAPPED',
      'team_id', v_team_id,
      'alias_id', v_alias.id
    ),
    true
  );

  return v_team_id;
end;
$$;

create or replace function public.get_team_merge_impact(
  p_source_team_id integer,
  p_target_team_id integer
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_source public.teams;
  v_target public.teams;
begin
  if p_source_team_id = p_target_team_id then
    raise exception '서로 다른 팀을 선택해주세요';
  end if;

  select * into v_source
  from public.teams
  where id = p_source_team_id and is_active;

  select * into v_target
  from public.teams
  where id = p_target_team_id and is_active;

  if v_source.id is null or v_target.id is null then
    raise exception '병합할 활성 팀을 찾을 수 없습니다';
  end if;

  return jsonb_build_object(
    'source_team_id', v_source.id,
    'source_team_name', v_source.name,
    'target_team_id', v_target.id,
    'target_team_name', v_target.name,
    'affected_matches', (
      select count(*)
      from public.games
      where home_team_id = v_source.id or away_team_id = v_source.id
    ),
    'affected_members', (
      select count(*)
      from public.users
      where favorite_team_id = v_source.id
    ),
    'affected_aliases', (
      select count(*)
      from public.team_aliases
      where team_id = v_source.id and is_active
    )
  );
end;
$$;

create or replace function public.admin_merge_teams(
  p_operator_id uuid,
  p_source_team_id integer,
  p_target_team_id integer
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_source public.teams;
  v_target public.teams;
  v_impact jsonb;
  v_moved_home integer;
  v_moved_away integer;
  v_moved_members integer;
begin
  if p_source_team_id = p_target_team_id then
    raise exception '서로 다른 팀을 선택해주세요';
  end if;

  select * into v_source
  from public.teams
  where id = p_source_team_id and is_active
  for update;

  select * into v_target
  from public.teams
  where id = p_target_team_id and is_active
  for update;

  if v_source.id is null or v_target.id is null then
    raise exception '병합할 활성 팀을 찾을 수 없습니다';
  end if;

  if exists (
    select 1
    from public.games
    where (
      home_team_id = v_source.id and away_team_id = v_target.id
    ) or (
      home_team_id = v_target.id and away_team_id = v_source.id
    )
  ) then
    raise exception '두 팀이 같은 경기의 홈/원정으로 연결되어 있어 병합할 수 없습니다';
  end if;

  v_impact := public.get_team_merge_impact(
    p_source_team_id,
    p_target_team_id
  );

  update public.games
  set home_team_id = v_target.id
  where home_team_id = v_source.id;
  get diagnostics v_moved_home = row_count;

  update public.games
  set away_team_id = v_target.id
  where away_team_id = v_source.id;
  get diagnostics v_moved_away = row_count;

  update public.users
  set favorite_team_id = v_target.id
  where favorite_team_id = v_source.id;
  get diagnostics v_moved_members = row_count;

  delete from public.team_aliases source_alias
  using public.team_aliases target_alias
  where source_alias.team_id = v_source.id
    and source_alias.is_active
    and target_alias.team_id = v_target.id
    and target_alias.is_active
    and upper(btrim(source_alias.source)) =
        upper(btrim(target_alias.source))
    and source_alias.normalized_alias = target_alias.normalized_alias;

  update public.team_aliases
  set team_id = v_target.id,
      updated_at = now()
  where team_id = v_source.id;

  update public.team_mapping_requests
  set mapped_team_id = v_target.id
  where mapped_team_id = v_source.id;

  update public.teams
  set is_active = false,
      merged_into_team_id = v_target.id,
      updated_at = now()
  where id = v_source.id;

  insert into public.admin_audit_logs (
    operator_id, action, target_type, target_id,
    before_state, after_state, success
  )
  values (
    p_operator_id,
    'TEAM_MERGE',
    'team',
    v_target.id::text,
    jsonb_build_object(
      'source', to_jsonb(v_source),
      'target', to_jsonb(v_target),
      'impact', v_impact
    ),
    jsonb_build_object(
      'source_team_id', v_source.id,
      'target_team_id', v_target.id,
      'moved_home_matches', v_moved_home,
      'moved_away_matches', v_moved_away,
      'moved_members', v_moved_members
    ),
    true
  );

  insert into public.admin_audit_logs (
    operator_id, action, target_type, target_id,
    before_state, after_state, success
  )
  values (
    p_operator_id,
    'TEAM_DEACTIVATE',
    'team',
    v_source.id::text,
    to_jsonb(v_source),
    jsonb_build_object(
      'is_active', false,
      'merged_into_team_id', v_target.id
    ),
    true
  );

  return v_impact || jsonb_build_object(
    'moved_home_matches', v_moved_home,
    'moved_away_matches', v_moved_away,
    'moved_members', v_moved_members
  );
end;
$$;

revoke all on table public.team_aliases from anon, authenticated;
revoke all on table public.team_mapping_requests from anon, authenticated;
grant select, insert, update, delete on table public.team_aliases to service_role;
grant select, insert, update, delete on table public.team_mapping_requests
  to service_role;
grant usage, select on sequence public.team_aliases_id_seq to service_role;
grant usage, select on sequence public.team_mapping_requests_id_seq
  to service_role;

revoke all on function public.admin_upsert_team(uuid, integer, text, text, text)
  from public, anon, authenticated;
revoke all on function public.admin_upsert_team_alias(
  uuid, bigint, text, text, integer
) from public, anon, authenticated;
revoke all on function public.resolve_team_mappings(text, text[])
  from public, anon, authenticated;
revoke all on function public.admin_approve_team_mapping(
  uuid, bigint, integer, text, text, text
) from public, anon, authenticated;
revoke all on function public.get_team_merge_impact(integer, integer)
  from public, anon, authenticated;
revoke all on function public.admin_merge_teams(uuid, integer, integer)
  from public, anon, authenticated;

grant execute on function public.admin_upsert_team(
  uuid, integer, text, text, text
) to service_role;
grant execute on function public.admin_upsert_team_alias(
  uuid, bigint, text, text, integer
) to service_role;
grant execute on function public.resolve_team_mappings(text, text[])
  to service_role;
grant execute on function public.admin_approve_team_mapping(
  uuid, bigint, integer, text, text, text
) to service_role;
grant execute on function public.get_team_merge_impact(integer, integer)
  to service_role;
grant execute on function public.admin_merge_teams(uuid, integer, integer)
  to service_role;
