-- Issue #36: server-authorized operator accounts, sessions, and audit trail.

do $$
begin
  create type public.admin_role as enum ('OWNER', 'OPERATOR', 'VIEWER');
exception
  when duplicate_object then null;
end;
$$;

create table if not exists public.admin_operators (
  id uuid primary key default gen_random_uuid(),
  username text not null,
  display_name text not null,
  role public.admin_role not null default 'VIEWER',
  password_hash text not null,
  is_active boolean not null default true,
  must_change_password boolean not null default true,
  created_by uuid references public.admin_operators(id) on delete set null,
  last_login_at timestamptz,
  password_changed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint admin_operators_username_format
    check (username = lower(username) and username ~ '^[a-z0-9._-]{3,50}$')
);

create unique index if not exists admin_operators_username_lower_key
  on public.admin_operators (lower(username));

create table if not exists public.admin_sessions (
  id uuid primary key default gen_random_uuid(),
  operator_id uuid not null
    references public.admin_operators(id) on delete cascade,
  token_hash text not null unique,
  expires_at timestamptz not null,
  reauthenticated_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  revoked_at timestamptz,
  created_at timestamptz not null default now()
);

create index if not exists admin_sessions_operator_active_idx
  on public.admin_sessions (operator_id, expires_at)
  where revoked_at is null;

create table if not exists public.admin_audit_logs (
  id bigint generated by default as identity primary key,
  request_id uuid not null default gen_random_uuid(),
  operator_id uuid references public.admin_operators(id) on delete set null,
  action text not null,
  target_type text,
  target_id text,
  before_state jsonb,
  after_state jsonb,
  success boolean not null,
  error_message text,
  ip_address inet,
  user_agent text,
  created_at timestamptz not null default now()
);

create index if not exists admin_audit_logs_operator_created_idx
  on public.admin_audit_logs (operator_id, created_at desc);

create index if not exists admin_audit_logs_action_created_idx
  on public.admin_audit_logs (action, created_at desc);

drop trigger if exists trg_admin_operators_set_updated_at
  on public.admin_operators;
create trigger trg_admin_operators_set_updated_at
before update on public.admin_operators
for each row execute function public.set_updated_at();

alter table public.admin_operators enable row level security;
alter table public.admin_sessions enable row level security;
alter table public.admin_audit_logs enable row level security;

revoke all on public.admin_operators from public, anon, authenticated;
revoke all on public.admin_sessions from public, anon, authenticated;
revoke all on public.admin_audit_logs from public, anon, authenticated;
grant select, insert, update, delete on public.admin_operators to service_role;
grant select, insert, update, delete on public.admin_sessions to service_role;
grant select, insert on public.admin_audit_logs to service_role;
grant usage, select on sequence public.admin_audit_logs_id_seq to service_role;

revoke execute on function public.create_season(text, date, date)
  from public, anon, authenticated;
revoke execute on function public.activate_season(integer)
  from public, anon, authenticated;
revoke execute on function public.end_season(integer)
  from public, anon, authenticated;
revoke execute on function public.create_market(
  integer,
  numeric,
  numeric,
  numeric
)
  from public, anon, authenticated;
revoke execute on function public.settle_market(integer, text)
  from public, anon, authenticated;
revoke execute on function public.close_market(integer)
  from public, anon, authenticated;
revoke execute on function public.cancel_market(integer)
  from public, anon, authenticated;
revoke execute on function public.set_liquidity_b(numeric)
  from public, anon, authenticated;
revoke execute on function public.distribute_weekly_coins(numeric)
  from public, anon, authenticated;
revoke execute on function public.admin_grant_coins(uuid, numeric)
  from public, anon, authenticated;
revoke execute on function public.admin_reset_password(bigint)
  from public, anon, authenticated;

grant execute on function public.create_season(text, date, date)
  to service_role;
grant execute on function public.activate_season(integer)
  to service_role;
grant execute on function public.end_season(integer)
  to service_role;
grant execute on function public.create_market(
  integer,
  numeric,
  numeric,
  numeric
)
  to service_role;
grant execute on function public.settle_market(integer, text)
  to service_role;
grant execute on function public.close_market(integer)
  to service_role;
grant execute on function public.cancel_market(integer)
  to service_role;
grant execute on function public.set_liquidity_b(numeric)
  to service_role;
grant execute on function public.distribute_weekly_coins(numeric)
  to service_role;
grant execute on function public.admin_grant_coins(uuid, numeric)
  to service_role;
grant execute on function public.admin_reset_password(bigint)
  to service_role;

revoke insert, update, delete on public.games
  from anon, authenticated;
revoke insert, update, delete on public.teams
  from anon, authenticated;
grant select on public.games, public.teams to anon, authenticated;
grant select, insert, update, delete on public.games, public.teams
  to service_role;
