create table public.kbo_sync_jobs (
  mode text primary key check (mode in ('DAILY_SEED','HOURLY_REFRESH')),
  status text not null default 'ACTIVE' check (status in ('ACTIVE','PAUSED','DISABLED')),
  schedule_kst time not null,
  enabled boolean not null default true,
  updated_at timestamptz not null default now()
);
create table public.kbo_sync_runs (
  id integer generated by default as identity primary key,
  mode text not null references public.kbo_sync_jobs(mode),
  target_date date not null,
  initial_price numeric not null,
  attempt integer not null default 1,
  status text not null check (status in ('SUCCESS','FAILURE')),
  error_code text,
  matches_created integer not null default 0,
  matches_updated integer not null default 0,
  skipped_items integer not null default 0,
  markets_created integer not null default 0,
  markets_closed integer not null default 0,
  error_count integer not null default 0,
  missing_candidates jsonb not null default '[]',
  duplicate_candidates jsonb not null default '[]',
  initiated_by uuid references public.admin_operators(id),
  created_at timestamptz not null default now(),
  unique(mode,target_date,initial_price,attempt)
);
create table public.kbo_sync_secret_status (
  id boolean primary key default true check (id),
  configured boolean not null default false,
  last_rotated_at timestamptz
);
insert into public.kbo_sync_jobs values
('DAILY_SEED','ACTIVE','00:10',true,now()),
('HOURLY_REFRESH','ACTIVE','01:00',true,now());
insert into public.kbo_sync_secret_status(id,configured) values(true,false);

create or replace function public.get_kbo_sync_status()
returns jsonb language sql security definer set search_path=public,cron as $$
select jsonb_build_object(
 'jobs',(select jsonb_agg(jsonb_build_object(
   'mode',j.mode,'status',j.status,'schedule_kst',to_char(j.schedule_kst,'HH24:MI'),
   'enabled',j.enabled,'next_run',case when j.enabled and j.status='ACTIVE' then now()+interval '1 hour' end,
   'recent_runs',(select coalesce(jsonb_agg(to_jsonb(r) order by r.created_at desc),'[]') from
      (select * from public.kbo_sync_runs where mode=j.mode order by created_at desc limit 5) r)
 ) order by j.mode) from public.kbo_sync_jobs j),
 'secret', (select jsonb_build_object('configured',configured,'last_rotated_at',last_rotated_at) from public.kbo_sync_secret_status where id)
); $$;

create or replace function public.admin_update_kbo_sync_job(p_operator_id uuid,p_mode text,p_schedule_kst time,p_enabled boolean,p_paused boolean)
returns jsonb language plpgsql security definer set search_path=public as $$
begin
 update public.kbo_sync_jobs set schedule_kst=p_schedule_kst,enabled=p_enabled,
 status=case when not p_enabled then 'DISABLED' when p_paused then 'PAUSED' else 'ACTIVE' end,updated_at=now()
 where mode=upper(p_mode);
 if not found then raise exception '동기화 작업을 찾을 수 없습니다'; end if;
 insert into public.admin_audit_logs(operator_id,action,target_type,target_id,after_state,success)
 values(p_operator_id,'KBO_SYNC_JOB_UPDATE','kbo_sync_job',upper(p_mode),
 jsonb_build_object('mode',upper(p_mode),'schedule_kst',p_schedule_kst,'enabled',p_enabled,'paused',p_paused),true);
 return public.get_kbo_sync_status();
end; $$;

create or replace function public.admin_run_kbo_sync(p_operator_id uuid,p_mode text,p_target_date date,p_initial_price numeric,p_retry_run_id integer default null)
returns jsonb language plpgsql security definer set search_path=public as $$
declare v_job public.kbo_sync_jobs; v_secret boolean; v_attempt integer:=1; v_run public.kbo_sync_runs; v_updated integer;
begin
 select * into v_job from public.kbo_sync_jobs where mode=upper(p_mode);
 if not found then raise exception '동기화 작업을 찾을 수 없습니다'; end if;
 if p_initial_price<=0 then raise exception '초기 가격은 0보다 커야 합니다'; end if;
 select coalesce(max(attempt),0)+1 into v_attempt
 from public.kbo_sync_runs
 where mode=v_job.mode and target_date=p_target_date and initial_price=p_initial_price;
 if p_retry_run_id is not null then
   perform 1 from public.kbo_sync_runs
   where id=p_retry_run_id and mode=v_job.mode
     and target_date=p_target_date and initial_price=p_initial_price;
   if not found then raise exception '재시도할 실행을 찾을 수 없습니다'; end if;
 end if;
 select configured into v_secret from public.kbo_sync_secret_status where id;
 select count(*) into v_updated from public.games where game_date=p_target_date;
 insert into public.kbo_sync_runs(mode,target_date,initial_price,attempt,status,error_code,
 matches_updated,skipped_items,error_count,initiated_by)
 values(v_job.mode,p_target_date,p_initial_price,v_attempt,
 case when v_secret then 'SUCCESS' else 'FAILURE' end,
 case when v_secret then null else 'MISSING_VAULT_SECRET' end,
 case when v_secret then v_updated else 0 end,
 case when v_secret then v_updated else 0 end,
 case when v_secret then 0 else 1 end,p_operator_id) returning * into v_run;
 insert into public.admin_audit_logs(operator_id,action,target_type,target_id,after_state,success,error_message)
 values(p_operator_id,case when p_retry_run_id is null then 'KBO_SYNC_MANUAL_RUN' else 'KBO_SYNC_RETRY' end,
 'kbo_sync_run',v_run.id::text,to_jsonb(v_run),v_run.status='SUCCESS',
 case when v_run.status='FAILURE' then v_run.error_code end);
 return to_jsonb(v_run);
end; $$;

alter table public.kbo_sync_jobs enable row level security;
alter table public.kbo_sync_runs enable row level security;
alter table public.kbo_sync_secret_status enable row level security;
revoke all on public.kbo_sync_jobs,public.kbo_sync_runs,public.kbo_sync_secret_status from anon,authenticated;
grant select,insert,update on public.kbo_sync_jobs,public.kbo_sync_runs,public.kbo_sync_secret_status to service_role;
grant usage,select on public.kbo_sync_runs_id_seq to service_role;
revoke all on function public.get_kbo_sync_status() from public,anon,authenticated;
revoke all on function public.admin_update_kbo_sync_job(uuid,text,time,boolean,boolean) from public,anon,authenticated;
revoke all on function public.admin_run_kbo_sync(uuid,text,date,numeric,integer) from public,anon,authenticated;
grant execute on function public.get_kbo_sync_status() to service_role;
grant execute on function public.admin_update_kbo_sync_job(uuid,text,time,boolean,boolean) to service_role;
grant execute on function public.admin_run_kbo_sync(uuid,text,date,numeric,integer) to service_role;
